/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package gui;

import gui.custom.CustomRectangularButton;
import enums.*;
import java.awt.*;
import java.awt.event.MouseEvent;
import javax.swing.*;
import javax.swing.JPanel;
/**
 *
 * @author Trần Ngọc Huyền
 */
public class GUI_Main extends javax.swing.JFrame {

    /**
     * Creates new form GUI_Main
     */
    private CreateOrder tabCreateOrder;
    private ManageBills tabBill;
    private ManageCategories tabCategory;
    private ManageBeverages tabBeverage;
    private ManageCustomers tabCustomer;
    private ManageEmployees tabEmployee;
    private Stats tabStats;
    private TabMainMenu currentSelectedTab;
    private JButton isFocusTab;

    public GUI_Main() {
        initComponents();
        lblNameEmp.setText(GUI_Login.e.getName());
        //Khởi tạo tab
        tabCreateOrder = new CreateOrder();
        tabBill = new ManageBills();
        tabCategory = new ManageCategories();
        tabBeverage = new ManageBeverages();
        tabCustomer = new ManageCustomers();
        tabEmployee = new ManageEmployees();
        tabStats = new Stats();
        currentSelectedTab = TabMainMenu.NULL;
        tabSwitcher(tabCreateOrder, TabMainMenu.ORDER, panelCreateOrder);
        setExtendedState(JFrame.MAXIMIZED_BOTH);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panelHead = new javax.swing.JPanel();
        jPanel1 = new javax.swing.JPanel();
        lblIcon = new javax.swing.JLabel();
        lblName = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        lblNameEmp = new javax.swing.JLabel();
        panelNav = new javax.swing.JPanel();
        panelMenu = new javax.swing.JPanel();
        panelCreateOrder = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        panelManageBill = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        panelManageCategory = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        panelManageBeverage = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        panelManageEmployee = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        panelManageCustomer = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        panelStats = new javax.swing.JPanel();
        jLabel7 = new javax.swing.JLabel();
        panelLogout = new javax.swing.JPanel();
        btnLogout = new CustomRectangularButton(new Color[]{Color.WHITE, new Color(102, 44, 33), new Color(118, 68, 52)});
        panelRight = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        panelHead.setBackground(new java.awt.Color(102, 44, 33));
        panelHead.setPreferredSize(new java.awt.Dimension(1059, 70));
        panelHead.setLayout(new java.awt.BorderLayout());

        jPanel1.setBackground(new java.awt.Color(102, 44, 33));

        lblIcon.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/icons8-coffee-beans-64.png"))); // NOI18N
        lblIcon.setPreferredSize(new java.awt.Dimension(100, 100));

        lblName.setFont(new java.awt.Font("Segoe UI", 3, 36)); // NOI18N
        lblName.setForeground(new java.awt.Color(255, 255, 255));
        lblName.setText("Zenta Coffee");
        lblName.setPreferredSize(new java.awt.Dimension(218, 100));

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(10, 10, 10)
                .addComponent(lblIcon, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(lblName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(lblIcon, javax.swing.GroupLayout.DEFAULT_SIZE, 70, Short.MAX_VALUE)
            .addComponent(lblName, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
        );

        panelHead.add(jPanel1, java.awt.BorderLayout.WEST);

        jPanel2.setBackground(new java.awt.Color(102, 44, 33));

        lblNameEmp.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        lblNameEmp.setForeground(new java.awt.Color(255, 255, 255));
        lblNameEmp.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lblNameEmp.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/icons8-user-30.png"))); // NOI18N
        lblNameEmp.setText("tnhxinhdep");
        lblNameEmp.setIconTextGap(10);
        lblNameEmp.setPreferredSize(new java.awt.Dimension(48, 48));

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblNameEmp, javax.swing.GroupLayout.PREFERRED_SIZE, 233, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(15, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap(20, Short.MAX_VALUE)
                .addComponent(lblNameEmp, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(20, Short.MAX_VALUE))
        );

        panelHead.add(jPanel2, java.awt.BorderLayout.EAST);

        getContentPane().add(panelHead, java.awt.BorderLayout.NORTH);

        panelNav.setBackground(new java.awt.Color(102, 44, 33));
        panelNav.setMinimumSize(new java.awt.Dimension(250, 180));
        panelNav.setPreferredSize(new java.awt.Dimension(300, 464));
        panelNav.setLayout(new java.awt.BorderLayout());

        panelMenu.setBackground(new java.awt.Color(102, 44, 33));

        panelCreateOrder.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                panelCreateOrderMouseClicked(evt);
            }
        });

        jLabel1.setBackground(new java.awt.Color(102, 44, 33));
        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/icons8-cart-48.png"))); // NOI18N
        jLabel1.setText("Bán hàng");
        jLabel1.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jLabel1.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);

        javax.swing.GroupLayout panelCreateOrderLayout = new javax.swing.GroupLayout(panelCreateOrder);
        panelCreateOrder.setLayout(panelCreateOrderLayout);
        panelCreateOrderLayout.setHorizontalGroup(
            panelCreateOrderLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        panelCreateOrderLayout.setVerticalGroup(
            panelCreateOrderLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, 100, Short.MAX_VALUE)
        );

        panelManageBill.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                panelManageBillMouseClicked(evt);
            }
        });

        jLabel2.setBackground(new java.awt.Color(102, 44, 33));
        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/icons8-bill-48.png"))); // NOI18N
        jLabel2.setText("Hoá đơn");
        jLabel2.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jLabel2.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);

        javax.swing.GroupLayout panelManageBillLayout = new javax.swing.GroupLayout(panelManageBill);
        panelManageBill.setLayout(panelManageBillLayout);
        panelManageBillLayout.setHorizontalGroup(
            panelManageBillLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, 300, Short.MAX_VALUE)
        );
        panelManageBillLayout.setVerticalGroup(
            panelManageBillLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, 100, Short.MAX_VALUE)
        );

        panelManageCategory.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                panelManageCategoryMouseClicked(evt);
            }
        });

        jLabel3.setBackground(new java.awt.Color(102, 44, 33));
        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/icons8-restaurant-menu-48.png"))); // NOI18N
        jLabel3.setText("Danh mục");
        jLabel3.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jLabel3.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);

        javax.swing.GroupLayout panelManageCategoryLayout = new javax.swing.GroupLayout(panelManageCategory);
        panelManageCategory.setLayout(panelManageCategoryLayout);
        panelManageCategoryLayout.setHorizontalGroup(
            panelManageCategoryLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, 300, Short.MAX_VALUE)
        );
        panelManageCategoryLayout.setVerticalGroup(
            panelManageCategoryLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, 100, Short.MAX_VALUE)
        );

        panelManageBeverage.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                panelManageBeverageMouseClicked(evt);
            }
        });

        jLabel4.setBackground(new java.awt.Color(102, 44, 33));
        jLabel4.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/icons8-coffee-48.png"))); // NOI18N
        jLabel4.setText("Menu thức uống");
        jLabel4.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jLabel4.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);

        javax.swing.GroupLayout panelManageBeverageLayout = new javax.swing.GroupLayout(panelManageBeverage);
        panelManageBeverage.setLayout(panelManageBeverageLayout);
        panelManageBeverageLayout.setHorizontalGroup(
            panelManageBeverageLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, 300, Short.MAX_VALUE)
        );
        panelManageBeverageLayout.setVerticalGroup(
            panelManageBeverageLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, 100, Short.MAX_VALUE)
        );

        panelManageEmployee.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                panelManageEmployeeMouseClicked(evt);
            }
        });

        jLabel5.setBackground(new java.awt.Color(102, 44, 33));
        jLabel5.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/icons8-waiter-48.png"))); // NOI18N
        jLabel5.setText("Nhân viên");
        jLabel5.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jLabel5.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);

        javax.swing.GroupLayout panelManageEmployeeLayout = new javax.swing.GroupLayout(panelManageEmployee);
        panelManageEmployee.setLayout(panelManageEmployeeLayout);
        panelManageEmployeeLayout.setHorizontalGroup(
            panelManageEmployeeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel5, javax.swing.GroupLayout.DEFAULT_SIZE, 300, Short.MAX_VALUE)
        );
        panelManageEmployeeLayout.setVerticalGroup(
            panelManageEmployeeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel5, javax.swing.GroupLayout.DEFAULT_SIZE, 100, Short.MAX_VALUE)
        );

        panelManageCustomer.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                panelManageCustomerMouseClicked(evt);
            }
        });

        jLabel6.setBackground(new java.awt.Color(102, 44, 33));
        jLabel6.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/icons8-customer-48.png"))); // NOI18N
        jLabel6.setText("Khách hàng");
        jLabel6.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jLabel6.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);

        javax.swing.GroupLayout panelManageCustomerLayout = new javax.swing.GroupLayout(panelManageCustomer);
        panelManageCustomer.setLayout(panelManageCustomerLayout);
        panelManageCustomerLayout.setHorizontalGroup(
            panelManageCustomerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel6, javax.swing.GroupLayout.DEFAULT_SIZE, 300, Short.MAX_VALUE)
        );
        panelManageCustomerLayout.setVerticalGroup(
            panelManageCustomerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel6, javax.swing.GroupLayout.DEFAULT_SIZE, 100, Short.MAX_VALUE)
        );

        panelStats.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                panelStatsMouseClicked(evt);
            }
        });

        jLabel7.setBackground(new java.awt.Color(102, 44, 33));
        jLabel7.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/icons8-stats-48.png"))); // NOI18N
        jLabel7.setText("Thống kê");
        jLabel7.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jLabel7.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);

        javax.swing.GroupLayout panelStatsLayout = new javax.swing.GroupLayout(panelStats);
        panelStats.setLayout(panelStatsLayout);
        panelStatsLayout.setHorizontalGroup(
            panelStatsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel7, javax.swing.GroupLayout.DEFAULT_SIZE, 300, Short.MAX_VALUE)
        );
        panelStatsLayout.setVerticalGroup(
            panelStatsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel7, javax.swing.GroupLayout.DEFAULT_SIZE, 100, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout panelMenuLayout = new javax.swing.GroupLayout(panelMenu);
        panelMenu.setLayout(panelMenuLayout);
        panelMenuLayout.setHorizontalGroup(
            panelMenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panelCreateOrder, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(panelManageBill, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(panelManageCategory, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(panelManageBeverage, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(panelManageEmployee, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(panelManageCustomer, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(panelStats, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        panelMenuLayout.setVerticalGroup(
            panelMenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelMenuLayout.createSequentialGroup()
                .addContainerGap(10, Short.MAX_VALUE)
                .addComponent(panelCreateOrder, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 20, Short.MAX_VALUE)
                .addComponent(panelManageBill, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 20, Short.MAX_VALUE)
                .addComponent(panelManageCategory, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 20, Short.MAX_VALUE)
                .addComponent(panelManageBeverage, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 20, Short.MAX_VALUE)
                .addComponent(panelManageEmployee, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 20, Short.MAX_VALUE)
                .addComponent(panelManageCustomer, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 20, Short.MAX_VALUE)
                .addComponent(panelStats, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(525, 525, 525))
        );

        panelNav.add(panelMenu, java.awt.BorderLayout.NORTH);

        btnLogout.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        btnLogout.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/icons8-log-out-48.png"))); // NOI18N
        btnLogout.setText("Đăng xuất");
        btnLogout.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnLogout.setIconTextGap(10);
        btnLogout.setPreferredSize(new java.awt.Dimension(233, 90));
        btnLogout.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btnLogout.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLogoutActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout panelLogoutLayout = new javax.swing.GroupLayout(panelLogout);
        panelLogout.setLayout(panelLogoutLayout);
        panelLogoutLayout.setHorizontalGroup(
            panelLogoutLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(btnLogout, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        panelLogoutLayout.setVerticalGroup(
            panelLogoutLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelLogoutLayout.createSequentialGroup()
                .addComponent(btnLogout, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        panelNav.add(panelLogout, java.awt.BorderLayout.SOUTH);

        getContentPane().add(panelNav, java.awt.BorderLayout.WEST);

        panelRight.setBackground(new java.awt.Color(255, 255, 255));
        panelRight.setLayout(new java.awt.BorderLayout());

        panelRight.add(new gui.CreateOrder());

        getContentPane().add(panelRight, java.awt.BorderLayout.CENTER);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void panelCreateOrderMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_panelCreateOrderMouseClicked
        panelTabMouseClicked(evt);
    }//GEN-LAST:event_panelCreateOrderMouseClicked

    private void panelManageBillMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_panelManageBillMouseClicked
        panelTabMouseClicked(evt);
    }//GEN-LAST:event_panelManageBillMouseClicked

    private void panelManageCategoryMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_panelManageCategoryMouseClicked
       panelTabMouseClicked(evt);
    }//GEN-LAST:event_panelManageCategoryMouseClicked

    private void panelManageBeverageMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_panelManageBeverageMouseClicked
        panelTabMouseClicked(evt);
    }//GEN-LAST:event_panelManageBeverageMouseClicked

    private void panelManageEmployeeMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_panelManageEmployeeMouseClicked
       panelTabMouseClicked(evt);
    }//GEN-LAST:event_panelManageEmployeeMouseClicked

    private void panelManageCustomerMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_panelManageCustomerMouseClicked
        panelTabMouseClicked(evt);
    }//GEN-LAST:event_panelManageCustomerMouseClicked

    private void panelStatsMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_panelStatsMouseClicked
        panelTabMouseClicked(evt);
    }//GEN-LAST:event_panelStatsMouseClicked

    private void btnLogoutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLogoutActionPerformed
       new GUI_Login().setVisible(true);
       this.setVisible(false);
    }//GEN-LAST:event_btnLogoutActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(GUI_Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(GUI_Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(GUI_Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(GUI_Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new GUI_Main().setVisible(true);
            }
        });
    }

    private void panelTabMouseClicked(MouseEvent evt) {
        // Tab quản lí order
        if (evt.getSource().equals(panelCreateOrder)) {
            tabSwitcher(tabCreateOrder, TabMainMenu.ORDER, panelCreateOrder);
            return;
        }

        // Tab hóa đơn
        if (evt.getSource().equals(panelManageBill)) {
            gui.ManageBills.loadCurrentBills();
            tabSwitcher(tabBill, TabMainMenu.BILL, panelManageBill);
            return;
        }

         //Tab quản lí danh mục
        if (evt.getSource().equals(panelManageCategory)) {
            if(GUI_Login.e.getRole().equalsIgnoreCase("Nhân Viên")) {
                JOptionPane.showMessageDialog(this, "Vui lòng đăng nhập bằng tài khoản admin");
                return;
            }
            tabSwitcher(tabCategory, TabMainMenu.CATEGORY, panelManageCategory);
            return;
        }
        // Tab quản lí thức uống
        if (evt.getSource().equals(panelManageBeverage)) {
            if(GUI_Login.e.getRole().equalsIgnoreCase("Nhân Viên")) {
                JOptionPane.showMessageDialog(this, "Vui lòng đăng nhập bằng tài khoản admin");
                return;
            }
            tabSwitcher(tabBeverage, TabMainMenu.BEVERAGE, panelManageBeverage);
            return;
        }
        //Tab quản lí khách hàng
        if (evt.getSource().equals(panelManageCustomer)) {
            if(GUI_Login.e.getRole().equalsIgnoreCase("Nhân Viên")) {
                JOptionPane.showMessageDialog(this, "Vui lòng đăng nhập bằng tài khoản admin");
                return;
            }
            tabSwitcher(tabCustomer, TabMainMenu.CUSTOMER, panelManageCustomer);
            return;
        }
        // Tab quản lí nhân viên
        if (evt.getSource().equals(panelManageEmployee)) {
            if(GUI_Login.e.getRole().equalsIgnoreCase("Nhân Viên")) {
                JOptionPane.showMessageDialog(this, "Vui lòng đăng nhập bằng tài khoản admin");
                return;
            }
            tabSwitcher(tabEmployee, TabMainMenu.EMPLOYEE.EMPLOYEE, panelManageEmployee);
            return;
        }
//         Tab thống kê
        if (evt.getSource().equals(panelStats)) {
            tabSwitcher(tabStats, TabMainMenu.STATS, panelStats);
            return;
        }
    }

    private void tabSwitcher(JPanel panelChuyen, TabMainMenu tabMoi, JPanel panelTab) {
        if (currentSelectedTab == tabMoi) {
            return;
        }
        panelCreateOrder.setBackground(new Color(102, 44, 33));
        panelManageBill.setBackground(new Color(102, 44, 33));
        panelManageCategory.setBackground(new Color(102, 44, 33));
        panelManageBeverage.setBackground(new Color(102, 44, 33));
        panelManageEmployee.setBackground(new Color(102, 44, 33));
        panelManageCustomer.setBackground(new Color(102, 44, 33));
        panelStats.setBackground(new Color(102, 44, 33));
        
        panelTab.setBackground(new Color(118, 68, 52));
        
        currentSelectedTab = tabMoi;
        panelRight.removeAll();
        panelRight.add(panelChuyen, BorderLayout.CENTER);
        panelRight.revalidate();
        panelRight.repaint();

    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnLogout;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JLabel lblIcon;
    private javax.swing.JLabel lblName;
    private static javax.swing.JLabel lblNameEmp;
    private javax.swing.JPanel panelCreateOrder;
    private javax.swing.JPanel panelHead;
    private javax.swing.JPanel panelLogout;
    private javax.swing.JPanel panelManageBeverage;
    private javax.swing.JPanel panelManageBill;
    private javax.swing.JPanel panelManageCategory;
    private javax.swing.JPanel panelManageCustomer;
    private javax.swing.JPanel panelManageEmployee;
    private javax.swing.JPanel panelMenu;
    private javax.swing.JPanel panelNav;
    public static javax.swing.JPanel panelRight;
    private javax.swing.JPanel panelStats;
    // End of variables declaration//GEN-END:variables
}
