/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package gui;

import gui.custom.CustomScrollBarUI;
import dao.*;
import entities.*;
import java.awt.Color;
import java.awt.Component;
import java.awt.Dimension;
import java.awt.Font;
import java.util.List;
import javax.swing.JLabel;
import javax.swing.JOptionPane;
import javax.swing.JTable;
import javax.swing.SwingConstants;
import javax.swing.table.DefaultTableCellRenderer;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableColumn;
import javax.swing.table.TableColumnModel;

/**
 *
 * @author ACER
 */
public class ManageCustomers extends javax.swing.JPanel {

    private DAOCustomer db = new DAOCustomer();
    private DefaultTableModel tblModelCus;
    private int row;

    /**
     * Creates new form ManageCus
     */
    public ManageCustomers() {
        initComponents();
        loadData();
        int countCus = db.findAll().size();
        if (countCus > 0) {
            txtTotal.setText(countCus + "");
        } else {
            txtTotal.setText("0");
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panelNorth = new javax.swing.JPanel();
        jPanel1 = new javax.swing.JPanel();
        panelImage = new javax.swing.JPanel();
        lblImg = new javax.swing.JLabel();
        panelSearch = new javax.swing.JPanel();
        txtSearch = new javax.swing.JTextField();
        btnSearch = new javax.swing.JButton();
        lblSearch = new javax.swing.JLabel();
        panelInfo = new javax.swing.JPanel();
        panelName = new javax.swing.JPanel();
        lblNameCus = new javax.swing.JLabel();
        txtNameCus = new javax.swing.JTextField();
        errorName = new javax.swing.JLabel();
        panelSDT = new javax.swing.JPanel();
        lblSDT = new javax.swing.JLabel();
        txtSDT = new javax.swing.JTextField();
        errorSDT = new javax.swing.JLabel();
        panelButton = new javax.swing.JPanel();
        btnAdd = new javax.swing.JButton();
        btnUpdate = new javax.swing.JButton();
        panelCenter = new javax.swing.JPanel();
        scroll = new javax.swing.JScrollPane();
        tblCus = new javax.swing.JTable();
        panelSouth = new javax.swing.JPanel();
        panelTotal = new javax.swing.JPanel();
        lblTotal = new javax.swing.JLabel();
        txtTotal = new javax.swing.JLabel();

        setBackground(new java.awt.Color(255, 255, 255));
        setLayout(new java.awt.BorderLayout());

        panelNorth.setBackground(new java.awt.Color(210, 180, 160));

        jPanel1.setBackground(new java.awt.Color(210, 180, 160));

        panelImage.setBackground(new java.awt.Color(210, 180, 160));

        lblImg.setBackground(new java.awt.Color(210, 180, 160));
        lblImg.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/icons8-customer-100.png"))); // NOI18N
        panelImage.add(lblImg);

        panelSearch.setBackground(new java.awt.Color(210, 180, 160));

        txtSearch.setSelectionColor(new java.awt.Color(102, 44, 33));
        txtSearch.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtSearchActionPerformed(evt);
            }
        });

        btnSearch.setBackground(new java.awt.Color(102, 44, 33));
        btnSearch.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btnSearch.setForeground(new java.awt.Color(255, 255, 255));
        btnSearch.setText("Tìm");
        btnSearch.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSearchActionPerformed(evt);
            }
        });

        lblSearch.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        lblSearch.setText("Tìm kiếm");

        javax.swing.GroupLayout panelSearchLayout = new javax.swing.GroupLayout(panelSearch);
        panelSearch.setLayout(panelSearchLayout);
        panelSearchLayout.setHorizontalGroup(
            panelSearchLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelSearchLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(lblSearch)
                .addGap(0, 0, 0)
                .addComponent(txtSearch, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(btnSearch)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        panelSearchLayout.setVerticalGroup(
            panelSearchLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelSearchLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panelSearchLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(panelSearchLayout.createSequentialGroup()
                        .addComponent(btnSearch, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(1, 1, 1))
                    .addGroup(panelSearchLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(txtSearch, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(lblSearch)))
                .addContainerGap(9, Short.MAX_VALUE))
        );

        panelInfo.setBackground(new java.awt.Color(210, 180, 160));
        panelInfo.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));

        panelName.setBackground(new java.awt.Color(210, 180, 160));

        lblNameCus.setBackground(new java.awt.Color(255, 255, 255));
        lblNameCus.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        lblNameCus.setText("Tên khách hàng");

        txtNameCus.setSelectionColor(new java.awt.Color(102, 44, 33));
        txtNameCus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtNameCusActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout panelNameLayout = new javax.swing.GroupLayout(panelName);
        panelName.setLayout(panelNameLayout);
        panelNameLayout.setHorizontalGroup(
            panelNameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelNameLayout.createSequentialGroup()
                .addContainerGap(35, Short.MAX_VALUE)
                .addComponent(lblNameCus, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtNameCus, javax.swing.GroupLayout.PREFERRED_SIZE, 500, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(errorName, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(35, Short.MAX_VALUE))
        );
        panelNameLayout.setVerticalGroup(
            panelNameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelNameLayout.createSequentialGroup()
                .addGroup(panelNameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtNameCus, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(errorName, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblNameCus, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(12, 12, 12))
        );

        panelSDT.setBackground(new java.awt.Color(210, 180, 160));

        lblSDT.setBackground(new java.awt.Color(255, 255, 255));
        lblSDT.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        lblSDT.setText("Số điện thoại");

        txtSDT.setSelectionColor(new java.awt.Color(102, 44, 33));

        javax.swing.GroupLayout panelSDTLayout = new javax.swing.GroupLayout(panelSDT);
        panelSDT.setLayout(panelSDTLayout);
        panelSDTLayout.setHorizontalGroup(
            panelSDTLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelSDTLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(lblSDT, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtSDT, javax.swing.GroupLayout.PREFERRED_SIZE, 500, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(errorSDT, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(29, Short.MAX_VALUE))
        );
        panelSDTLayout.setVerticalGroup(
            panelSDTLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelSDTLayout.createSequentialGroup()
                .addGroup(panelSDTLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblSDT, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtSDT, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(errorSDT, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(0, 0, Short.MAX_VALUE))
        );

        lblSDT.setPreferredSize(lblNameCus.getPreferredSize());

        panelButton.setBackground(new java.awt.Color(210, 180, 160));

        btnAdd.setBackground(new java.awt.Color(102, 44, 33));
        btnAdd.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/icons8-plus-30.png"))); // NOI18N
        btnAdd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAddActionPerformed(evt);
            }
        });
        panelButton.add(btnAdd);

        btnUpdate.setBackground(new java.awt.Color(102, 44, 33));
        btnUpdate.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/icons8-edit-30 .png"))); // NOI18N
        btnUpdate.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        btnUpdate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnUpdateActionPerformed(evt);
            }
        });
        panelButton.add(btnUpdate);

        javax.swing.GroupLayout panelInfoLayout = new javax.swing.GroupLayout(panelInfo);
        panelInfo.setLayout(panelInfoLayout);
        panelInfoLayout.setHorizontalGroup(
            panelInfoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panelButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(panelInfoLayout.createSequentialGroup()
                .addComponent(panelName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelInfoLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(panelSDT, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        panelInfoLayout.setVerticalGroup(
            panelInfoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelInfoLayout.createSequentialGroup()
                .addComponent(panelName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(10, 10, 10)
                .addComponent(panelSDT, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(panelButton, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(panelInfo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(panelSearch, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(panelImage, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(panelImage, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(panelSearch, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(42, 42, 42)
                .addComponent(panelInfo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        panelNorth.add(jPanel1);

        add(panelNorth, java.awt.BorderLayout.NORTH);

        panelCenter.setBackground(new java.awt.Color(210, 180, 160));
        panelCenter.setLayout(new javax.swing.BoxLayout(panelCenter, javax.swing.BoxLayout.LINE_AXIS));

        scroll.setBackground(new java.awt.Color(255, 255, 255));
        scroll.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));

        String[] header = {"Mã khách hàng", "Tên", "Số điện thoại", "Điểm thưởng"};
        tblModelCus = new DefaultTableModel(header, 0) {
            boolean[] canEdit = new boolean[]{
                false, false, false, false
            };

            @Override
            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit[columnIndex];
            }
        };
        tblCus.setModel(tblModelCus);
        tblCus.setFont(new java.awt.Font("Segoe UI", 0, 16));
        tblCus.getTableHeader().setResizingAllowed(false);
        for (int i = 0; i < tblCus.getColumnCount(); i++) {
            tblCus.getColumnModel().getColumn(i).setResizable(false);
        }
        tblCus.getTableHeader().setPreferredSize(new Dimension(tblCus.getColumnModel().getTotalColumnWidth(), 50));
        tblCus.getTableHeader().setDefaultRenderer(new javax.swing.table.DefaultTableCellRenderer() {
            @Override
            public Component getTableCellRendererComponent(JTable table, Object value, boolean isSelected, boolean hasFocus, int row, int column) {
                JLabel label = (JLabel) super.getTableCellRendererComponent(table, value, isSelected, hasFocus, row, column);
                label.setBackground(new Color(235,228,226));  // Thiết lập màu nền
                label.setOpaque(true);  // Đảm bảo màu nền được áp dụng
                label.setFont(new Font("Segoe UI", Font.BOLD, 17));
                label.setHorizontalAlignment(SwingConstants.CENTER);  // Căn giữa văn bản
                return label;
            }
        });

        // Thiết lập DefaultTableCellRenderer để căn giữa
        DefaultTableCellRenderer centerRenderer = new DefaultTableCellRenderer();
        centerRenderer.setHorizontalAlignment(SwingConstants.CENTER);

        // Áp dụng renderer này cho tất cả các cột
        for (int i = 0; i < tblCus.getColumnCount(); i++) {
            TableColumn column = tblCus.getColumnModel().getColumn(i);
            column.setCellRenderer(centerRenderer);
        }

        tblCus.setRowHeight(50);

        tblCus.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_INTERVAL_SELECTION);

        tblCus.getTableHeader().setReorderingAllowed(false);

        TableColumnModel columnModel = tblCus.getColumnModel();
        TableColumn col0 = columnModel.getColumn(0);
        TableColumn col1 = columnModel.getColumn(1);
        TableColumn col2 = columnModel.getColumn(2);
        TableColumn col3 = columnModel.getColumn(3);

        col0.setPreferredWidth(30);
        col1.setPreferredWidth(120);
        col2.setPreferredWidth(20);
        col3.setPreferredWidth(80);

        tblCus.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);

        tblCus.getTableHeader().setResizingAllowed(false);
        for (int i = 0; i < tblCus.getColumnCount(); i++) {
            tblCus.getColumnModel().getColumn(i).setResizable(false);
        }
        tblCus.setModel(tblModelCus);
        tblCus.setSelectionBackground(new java.awt.Color(102, 44, 33));
        tblCus.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblCusMouseClicked(evt);
            }
        });
        scroll.setViewportView(tblCus);
        scroll.getVerticalScrollBar().setUI(new CustomScrollBarUI());
        scroll.getViewport().setBackground(new Color(235, 228, 226));

        panelCenter.add(scroll);

        add(panelCenter, java.awt.BorderLayout.CENTER);

        panelSouth.setBackground(new java.awt.Color(210, 180, 160));

        panelTotal.setBackground(new java.awt.Color(210, 180, 160));

        lblTotal.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        lblTotal.setText("Tổng khách hàng");

        txtTotal.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N

        javax.swing.GroupLayout panelTotalLayout = new javax.swing.GroupLayout(panelTotal);
        panelTotal.setLayout(panelTotalLayout);
        panelTotalLayout.setHorizontalGroup(
            panelTotalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelTotalLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(lblTotal, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(20, 20, 20)
                .addComponent(txtTotal, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        panelTotalLayout.setVerticalGroup(
            panelTotalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelTotalLayout.createSequentialGroup()
                .addGroup(panelTotalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblTotal, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(txtTotal, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );

        javax.swing.GroupLayout panelSouthLayout = new javax.swing.GroupLayout(panelSouth);
        panelSouth.setLayout(panelSouthLayout);
        panelSouthLayout.setHorizontalGroup(
            panelSouthLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
            .addGroup(panelSouthLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(panelSouthLayout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(panelTotal, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addContainerGap()))
        );
        panelSouthLayout.setVerticalGroup(
            panelSouthLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
            .addGroup(panelSouthLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelSouthLayout.createSequentialGroup()
                    .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(panelTotal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
        );

        add(panelSouth, java.awt.BorderLayout.SOUTH);
    }// </editor-fold>//GEN-END:initComponents

    private void btnSearchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSearchActionPerformed
        tblModelCus.setRowCount(0);
        String find = txtSearch.getText();
        Customer c = db.findByPhone(find);
        if (c != null) {
            tblModelCus.addRow(new Object[]{c.getCustomerID(), c.getName(), c.getPhoneNumber(), c.getRewardPoint()});

            int countCus = db.findAll().size();
            if (countCus > 0) {
                txtTotal.setText(countCus + "");
            } else {
                txtTotal.setText("0");
            }

            txtNameCus.setText(tblModelCus.getValueAt(row, 1).toString());
            txtSDT.setText(tblModelCus.getValueAt(row, 2).toString());
        } else {
            clearTextField();
            loadData();
            JOptionPane.showMessageDialog(this, "Không tìm thấy!");

        }
    }//GEN-LAST:event_btnSearchActionPerformed

    private void txtSearchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtSearchActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtSearchActionPerformed

    private void btnAddActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAddActionPerformed
        if (valiData()) {
            Customer cus = revertCustomerFromTextFields();
            db.insert(cus);
            tblModelCus.addRow(new Object[]{cus.getCustomerID(), cus.getName(), cus.getPhoneNumber(), cus.getRewardPoint()});
            int countCus = db.findAll().size();
            if (countCus > 0) {
                txtTotal.setText(countCus + "");
            } else {
                txtTotal.setText("0");
            }
            JOptionPane.showMessageDialog(this, "Thêm thành công!");
        }

    }//GEN-LAST:event_btnAddActionPerformed
    private void clearTextField() {
        txtNameCus.setText("");
        txtSDT.setText("");
        txtSearch.setText("");

    }

    private boolean valiData() {
        String nameCus = txtNameCus.getText().trim();
        String soDienThoai = txtSDT.getText().trim();
        if (nameCus.equals("")) {
            errorName.setForeground(Color.red);
            errorName.setText("Tên không hợp lệ!");
            return false;
        } else {
            errorName.setForeground(Color.green);
            errorName.setText("");

        }

        if (soDienThoai.equals("")) {
            errorSDT.setForeground(Color.red);
            errorSDT.setText("Số điện thoại không hợp lệ");
            return false;
        } else {
            errorSDT.setForeground(Color.green);
            errorSDT.setText("");

        }
        return true;
    }

    private Customer revertCustomerFromTextFields() {
        String nameCus = txtNameCus.getText().trim();
        String soDienThoai = txtSDT.getText().trim();
        return new Customer(nameCus, soDienThoai);
    }
    private void btnUpdateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnUpdateActionPerformed
        int row = tblCus.getSelectedRow();
        String name = txtNameCus.getText().trim();
        String sdt = txtSDT.getText().trim();
        if (valiData()) {
            Customer newCus = new Customer(tblModelCus.getValueAt(row, 0).toString(), name, sdt);
            int option = JOptionPane.showConfirmDialog(this, "Bạn có chắc chắn muốn cập nhật thông tin?", "Xác nhận", JOptionPane.YES_NO_OPTION);
            if (option == JOptionPane.YES_OPTION) {
                tblModelCus.setValueAt(name, row, 1);
                tblModelCus.setValueAt(sdt, row, 2);
                db.update(newCus);
                JOptionPane.showMessageDialog(this, "Cập nhật thông tin thành công!");
            }

        }
    }//GEN-LAST:event_btnUpdateActionPerformed

    private void tblCusMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblCusMouseClicked
        int row = tblCus.getSelectedRow();
        txtNameCus.setText(tblModelCus.getValueAt(row, 1).toString());
        txtSDT.setText(tblModelCus.getValueAt(row, 2).toString());
    }//GEN-LAST:event_tblCusMouseClicked

    private void txtNameCusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtNameCusActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtNameCusActionPerformed
    //không để static, sai đó dạ
    public void loadData() {
        List<Customer> listTopCus = db.getListTopCus();
        for (Customer cus : listTopCus) {
            if(cus.getCustomerID().equals("Cust0000"))
                return;
            tblModelCus.addRow(new Object[]{cus.getCustomerID(), cus.getName(), cus.getPhoneNumber(), cus.getRewardPoint()});
            int countCus = db.findAll().size();
            if (countCus > 0) {
                txtTotal.setText(countCus + "");
            } else {
                txtTotal.setText("0");
            }
        }
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAdd;
    private javax.swing.JButton btnSearch;
    private javax.swing.JButton btnUpdate;
    private javax.swing.JLabel errorName;
    private javax.swing.JLabel errorSDT;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel lblImg;
    private javax.swing.JLabel lblNameCus;
    private javax.swing.JLabel lblSDT;
    private javax.swing.JLabel lblSearch;
    private javax.swing.JLabel lblTotal;
    private javax.swing.JPanel panelButton;
    private javax.swing.JPanel panelCenter;
    private javax.swing.JPanel panelImage;
    private javax.swing.JPanel panelInfo;
    private javax.swing.JPanel panelName;
    private javax.swing.JPanel panelNorth;
    private javax.swing.JPanel panelSDT;
    private javax.swing.JPanel panelSearch;
    private javax.swing.JPanel panelSouth;
    private javax.swing.JPanel panelTotal;
    private javax.swing.JScrollPane scroll;
    public static javax.swing.JTable tblCus;
    private static javax.swing.JTextField txtNameCus;
    private static javax.swing.JTextField txtSDT;
    private javax.swing.JTextField txtSearch;
    private javax.swing.JLabel txtTotal;
    // End of variables declaration//GEN-END:variables
}
