/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package gui;


import gui.custom.CustomRectangularButton;
import gui.custom.CustomScrollBarUI;
import entities.*;
import dao.*;
import enums.*;
import java.awt.Color;
import java.awt.Component;
import java.awt.Dimension;
import java.awt.Font;
import java.sql.Connection;
import java.util.List;
import javax.swing.BorderFactory;
import javax.swing.JLabel;
import javax.swing.JOptionPane;
import javax.swing.JTable;
import javax.swing.SwingConstants;
import javax.swing.table.DefaultTableCellRenderer;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableColumn;
import javax.swing.table.TableColumnModel;

/**
 *
 * @author ADMIN
 */
public class ManageEmployees extends javax.swing.JPanel {

    private static Connection con;
    private static List<Employee> listTopEmp;
    private static DAOEmployee de = new DAOEmployee();
    private static DefaultTableModel tblModelEmp;
    private String imgPath;

    /**
     * Creates new form ManageEmployees
     */
    public ManageEmployees() {
        initComponents();
        loadData();
        int countCus = de.findAll().size();
        if (countCus > 0) {
            lblCountNV.setText(countCus + "");
        } else {
            lblCountNV.setText("0");
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        buttonGroup2 = new javax.swing.ButtonGroup();
        panelContent = new javax.swing.JPanel();
        panelRight = new javax.swing.JPanel();
        scroll = new javax.swing.JScrollPane();
        table = new javax.swing.JTable();
        panelCoutNV = new javax.swing.JPanel();
        lblCountNV = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        panelLeft = new javax.swing.JPanel();
        panelLeftTop = new javax.swing.JPanel();
        panelFind = new javax.swing.JPanel();
        lblTim = new javax.swing.JLabel();
        txtTim = new javax.swing.JTextField();
        btnSearch = new javax.swing.JButton();
        panelIconAccount = new javax.swing.JPanel();
        lblIconAccont = new javax.swing.JLabel();
        panelLeftBottom = new javax.swing.JPanel();
        panelTen = new javax.swing.JPanel();
        lblTen = new javax.swing.JLabel();
        txtTen = new javax.swing.JTextField();
        errorTen = new javax.swing.JLabel();
        lblSDT = new javax.swing.JLabel();
        txtSDT = new javax.swing.JTextField();
        errorSDT = new javax.swing.JLabel();
        panelCaLam = new javax.swing.JPanel();
        lblCaLam = new javax.swing.JLabel();
        radio1 = new javax.swing.JRadioButton();
        radio2 = new javax.swing.JRadioButton();
        radio3 = new javax.swing.JRadioButton();
        lblDiaChi = new javax.swing.JLabel();
        txtDiaChi = new javax.swing.JTextField();
        errorDiaChi = new javax.swing.JLabel();
        panelSDT = new javax.swing.JPanel();
        panelLuong = new javax.swing.JPanel();
        lblLuong2 = new javax.swing.JLabel();
        txtLuong = new javax.swing.JTextField();
        errorLuong = new javax.swing.JLabel();
        lblQuyen = new javax.swing.JLabel();
        radioQL = new javax.swing.JRadioButton();
        radioNV = new javax.swing.JRadioButton();
        panelButton = new javax.swing.JPanel();
        btnThem = new CustomRectangularButton(new Color[]{Color.WHITE, new Color(102, 44, 33), new Color(102, 44, 33)});
        btnSua = new CustomRectangularButton(new Color[]{Color.WHITE, new Color(102, 44, 33), new Color(102, 44, 33)});

        buttonGroup1.add(radio1);
        buttonGroup1.add(radio2);
        buttonGroup1.add(radio3);

        buttonGroup2.add(radioQL);
        buttonGroup2.add(radioNV);

        setLayout(new java.awt.BorderLayout());

        panelContent.setBackground(new java.awt.Color(210, 180, 160));
        panelContent.setLayout(new java.awt.BorderLayout());

        panelRight.setBackground(new java.awt.Color(210, 180, 160));

        scroll.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                scrollMouseClicked(evt);
            }
        });

        String[] header = {"Mã", "Tên Nhân Viên", "Ca làm", "Lương", "Số điện thoại", "Địa chỉ", "Phân quyền"};
        tblModelEmp = new DefaultTableModel(header, 0) {
            boolean[] canEdit = new boolean[]{
                false, false, false, false, false, false, false
            };

            @Override
            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit[columnIndex];
            }
        };
        table.setModel(tblModelEmp);
        table.setFont(new java.awt.Font("Segoe UI", 0, 16));
        table.getTableHeader().setResizingAllowed(false);
        for (int i = 0; i < table.getColumnCount(); i++) {
            table.getColumnModel().getColumn(i).setResizable(false);
        }
        table.getTableHeader().setPreferredSize(new Dimension(table.getColumnModel().getTotalColumnWidth(), 50));
        table.getTableHeader().setBorder(BorderFactory.createMatteBorder(0, 0, 1, 0, new Color(102, 44, 33)));
        table.getTableHeader().setDefaultRenderer(new javax.swing.table.DefaultTableCellRenderer() {
            @Override
            public Component getTableCellRendererComponent(JTable table, Object value, boolean isSelected, boolean hasFocus, int row, int column) {
                JLabel label = (JLabel) super.getTableCellRendererComponent(table, value, isSelected, hasFocus, row, column);
                label.setBackground(new Color(235,238,236));  // Thiết lập màu nền
                label.setOpaque(true);  // Đảm bảo màu nền được áp dụng
                label.setFont(new Font("Segoe UI", Font.BOLD, 17));
                label.setHorizontalAlignment(SwingConstants.CENTER);  // Căn giữa văn bản
                return label;
            }
        });

        // Thiết lập DefaultTableCellRenderer để căn giữa
        DefaultTableCellRenderer centerRenderer = new DefaultTableCellRenderer();
        centerRenderer.setHorizontalAlignment(SwingConstants.CENTER);

        // Áp dụng renderer này cho tất cả các cột
        for (int i = 0; i < table.getColumnCount(); i++) {
            TableColumn column = table.getColumnModel().getColumn(i);
            column.setCellRenderer(centerRenderer);
        }

        table.setRowHeight(50);

        table.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_INTERVAL_SELECTION);

        table.getTableHeader().setReorderingAllowed(false);

        TableColumnModel columnModel = table.getColumnModel();
        TableColumn col0 = columnModel.getColumn(0);
        TableColumn col1 = columnModel.getColumn(1);
        TableColumn col2 = columnModel.getColumn(2);
        TableColumn col3 = columnModel.getColumn(3);
        TableColumn col4 = columnModel.getColumn(4);

        col0.setPreferredWidth(30);
        col1.setPreferredWidth(120);
        col2.setPreferredWidth(20);
        col3.setPreferredWidth(80);
        col4.setPreferredWidth(100);
        table.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);

        table.getTableHeader().setResizingAllowed(false);
        for (int i = 0; i < table.getColumnCount(); i++) {
            table.getColumnModel().getColumn(i).setResizable(false);
        }
        table.setSelectionBackground(new java.awt.Color(102, 44, 33));
        table.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tableMouseClicked(evt);
            }
        });
        scroll.setViewportView(table);
        scroll.getViewport().setBackground(new Color(235, 228, 226));
        scroll.getVerticalScrollBar().setUI(new CustomScrollBarUI());

        panelCoutNV.setBackground(new java.awt.Color(211, 180, 160));

        lblCountNV.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N

        jLabel2.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel2.setText("Tổng số nhân viên: ");

        javax.swing.GroupLayout panelCoutNVLayout = new javax.swing.GroupLayout(panelCoutNV);
        panelCoutNV.setLayout(panelCoutNVLayout);
        panelCoutNVLayout.setHorizontalGroup(
            panelCoutNVLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelCoutNVLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 168, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblCountNV, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        panelCoutNVLayout.setVerticalGroup(
            panelCoutNVLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(lblCountNV, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(panelCoutNVLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, 43, Short.MAX_VALUE)
                .addContainerGap())
        );

        javax.swing.GroupLayout panelRightLayout = new javax.swing.GroupLayout(panelRight);
        panelRight.setLayout(panelRightLayout);
        panelRightLayout.setHorizontalGroup(
            panelRightLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(scroll, javax.swing.GroupLayout.DEFAULT_SIZE, 2241, Short.MAX_VALUE)
            .addComponent(panelCoutNV, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        panelRightLayout.setVerticalGroup(
            panelRightLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelRightLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(scroll, javax.swing.GroupLayout.PREFERRED_SIZE, 261, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(panelCoutNV, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        panelContent.add(panelRight, java.awt.BorderLayout.PAGE_START);

        panelLeft.setBackground(new java.awt.Color(210, 180, 160));

        panelLeftTop.setBackground(new java.awt.Color(210, 180, 160));

        panelFind.setBackground(new java.awt.Color(211, 180, 160));

        lblTim.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        lblTim.setText("Nhập mã nhân viên cần tìm");

        txtTim.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 10, 1, 1));
        txtTim.setPreferredSize(new java.awt.Dimension(64, 25));
        txtTim.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtTimActionPerformed(evt);
            }
        });

        btnSearch.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/icons8-search-24.png"))); // NOI18N
        btnSearch.setFocusPainted(false);
        btnSearch.setMargin(new java.awt.Insets(0, 0, 0, 0));
        btnSearch.setOpaque(true);
        btnSearch.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSearchActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout panelFindLayout = new javax.swing.GroupLayout(panelFind);
        panelFind.setLayout(panelFindLayout);
        panelFindLayout.setHorizontalGroup(
            panelFindLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelFindLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(lblTim)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtTim, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnSearch, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        panelFindLayout.setVerticalGroup(
            panelFindLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelFindLayout.createSequentialGroup()
                .addContainerGap(15, Short.MAX_VALUE)
                .addGroup(panelFindLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(panelFindLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(lblTim)
                        .addComponent(txtTim, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(btnSearch, javax.swing.GroupLayout.DEFAULT_SIZE, 28, Short.MAX_VALUE))
                .addContainerGap())
        );

        btnSearch.setBackground(Color.WHITE);

        panelIconAccount.setBackground(new java.awt.Color(211, 180, 160));

        lblIconAccont.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/icons8-account-100.png"))); // NOI18N

        javax.swing.GroupLayout panelIconAccountLayout = new javax.swing.GroupLayout(panelIconAccount);
        panelIconAccount.setLayout(panelIconAccountLayout);
        panelIconAccountLayout.setHorizontalGroup(
            panelIconAccountLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelIconAccountLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(lblIconAccont)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        panelIconAccountLayout.setVerticalGroup(
            panelIconAccountLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelIconAccountLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblIconAccont, javax.swing.GroupLayout.PREFERRED_SIZE, 89, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout panelLeftTopLayout = new javax.swing.GroupLayout(panelLeftTop);
        panelLeftTop.setLayout(panelLeftTopLayout);
        panelLeftTopLayout.setHorizontalGroup(
            panelLeftTopLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panelFind, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(panelIconAccount, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        panelLeftTopLayout.setVerticalGroup(
            panelLeftTopLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelLeftTopLayout.createSequentialGroup()
                .addGap(0, 0, 0)
                .addComponent(panelIconAccount, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(panelFind, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        panelLeftBottom.setBackground(new java.awt.Color(210, 180, 160));
        panelLeftBottom.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "THÔNG TIN", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Segoe UI", 0, 18))); // NOI18N

        panelTen.setBackground(new java.awt.Color(210, 180, 160));

        lblTen.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        lblTen.setText("Tên nhân viên:");

        txtTen.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 10, 1, 1));
        txtTen.setMinimumSize(new java.awt.Dimension(64, 25));
        txtTen.setPreferredSize(new java.awt.Dimension(64, 25));

        lblSDT.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        lblSDT.setText("Số điện thoại");

        txtSDT.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 10, 1, 1));
        txtSDT.setMinimumSize(new java.awt.Dimension(64, 25));
        txtSDT.setPreferredSize(new java.awt.Dimension(64, 25));
        txtSDT.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtSDTActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout panelTenLayout = new javax.swing.GroupLayout(panelTen);
        panelTen.setLayout(panelTenLayout);
        panelTenLayout.setHorizontalGroup(
            panelTenLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelTenLayout.createSequentialGroup()
                .addGap(125, 125, 125)
                .addComponent(lblTen, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(21, 21, 21)
                .addComponent(txtTen, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(errorTen, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(100, 100, 100)
                .addComponent(lblSDT, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(21, 21, 21)
                .addComponent(txtSDT, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(9, 9, 9)
                .addComponent(errorSDT, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        panelTenLayout.setVerticalGroup(
            panelTenLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelTenLayout.createSequentialGroup()
                .addContainerGap(82, Short.MAX_VALUE)
                .addGroup(panelTenLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(errorSDT, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(panelTenLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(lblSDT)
                        .addComponent(txtSDT, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(panelTenLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(errorTen, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGroup(panelTenLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblTen)
                            .addComponent(txtTen, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(7, 7, 7))
        );

        panelCaLam.setBackground(new java.awt.Color(210, 180, 160));

        lblCaLam.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        lblCaLam.setText("Ca làm:");

        radio1.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        radio1.setText("1");

        radio2.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        radio2.setText("2");
        radio2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                radio2ActionPerformed(evt);
            }
        });

        radio3.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        radio3.setText("3");

        lblDiaChi.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        lblDiaChi.setText("Địa chỉ:");

        txtDiaChi.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 10, 1, 1));
        txtDiaChi.setMinimumSize(new java.awt.Dimension(64, 25));
        txtDiaChi.setPreferredSize(new java.awt.Dimension(64, 25));
        txtDiaChi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtDiaChiActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout panelCaLamLayout = new javax.swing.GroupLayout(panelCaLam);
        panelCaLam.setLayout(panelCaLamLayout);
        panelCaLamLayout.setHorizontalGroup(
            panelCaLamLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelCaLamLayout.createSequentialGroup()
                .addGap(125, 125, 125)
                .addComponent(lblCaLam, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(21, 21, 21)
                .addComponent(radio1, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(radio2, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(radio3, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(335, 335, 335)
                .addComponent(lblDiaChi, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(21, 21, 21)
                .addComponent(txtDiaChi, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(errorDiaChi, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(846, Short.MAX_VALUE))
        );
        panelCaLamLayout.setVerticalGroup(
            panelCaLamLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelCaLamLayout.createSequentialGroup()
                .addGap(9, 9, 9)
                .addGroup(panelCaLamLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(errorDiaChi, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(panelCaLamLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(lblCaLam)
                        .addComponent(radio1)
                        .addComponent(radio2)
                        .addComponent(radio3)
                        .addComponent(lblDiaChi)
                        .addComponent(txtDiaChi, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(10, Short.MAX_VALUE))
        );

        panelSDT.setBackground(new java.awt.Color(210, 180, 160));

        javax.swing.GroupLayout panelSDTLayout = new javax.swing.GroupLayout(panelSDT);
        panelSDT.setLayout(panelSDTLayout);
        panelSDTLayout.setHorizontalGroup(
            panelSDTLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 2231, Short.MAX_VALUE)
        );
        panelSDTLayout.setVerticalGroup(
            panelSDTLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 42, Short.MAX_VALUE)
        );

        panelLuong.setBackground(new java.awt.Color(210, 180, 160));

        lblLuong2.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        lblLuong2.setText("Lương:");

        txtLuong.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 10, 1, 1));
        txtLuong.setMinimumSize(new java.awt.Dimension(64, 25));
        txtLuong.setPreferredSize(new java.awt.Dimension(64, 25));
        txtLuong.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtLuongActionPerformed(evt);
            }
        });

        lblQuyen.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        lblQuyen.setText("Phân quyền");

        radioQL.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        radioQL.setText("Quản lí");

        radioNV.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        radioNV.setText("Nhân viên");

        javax.swing.GroupLayout panelLuongLayout = new javax.swing.GroupLayout(panelLuong);
        panelLuong.setLayout(panelLuongLayout);
        panelLuongLayout.setHorizontalGroup(
            panelLuongLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelLuongLayout.createSequentialGroup()
                .addGap(125, 125, 125)
                .addComponent(lblLuong2, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(21, 21, 21)
                .addComponent(txtLuong, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(errorLuong, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(100, 100, 100)
                .addComponent(lblQuyen, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(21, 21, 21)
                .addComponent(radioQL, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(42, 42, 42)
                .addComponent(radioNV, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        panelLuongLayout.setVerticalGroup(
            panelLuongLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelLuongLayout.createSequentialGroup()
                .addGap(8, 8, 8)
                .addGroup(panelLuongLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelLuongLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(lblQuyen)
                        .addComponent(radioQL)
                        .addComponent(radioNV))
                    .addComponent(errorLuong, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(panelLuongLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(lblLuong2)
                        .addComponent(txtLuong, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        panelButton.setBackground(new java.awt.Color(210, 180, 160));

        btnThem.setBackground(new java.awt.Color(102, 44, 33));
        btnThem.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        btnThem.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/icons8-plus-30.png"))); // NOI18N
        btnThem.setMaximumSize(new java.awt.Dimension(72, 7));
        btnThem.setPreferredSize(new java.awt.Dimension(72, 7));
        btnThem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnThemActionPerformed(evt);
            }
        });

        btnSua.setBackground(new java.awt.Color(102, 44, 33));
        btnSua.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        btnSua.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/icons8-edit-30 .png"))); // NOI18N
        btnSua.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSuaActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout panelButtonLayout = new javax.swing.GroupLayout(panelButton);
        panelButton.setLayout(panelButtonLayout);
        panelButtonLayout.setHorizontalGroup(
            panelButtonLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelButtonLayout.createSequentialGroup()
                .addContainerGap(1058, Short.MAX_VALUE)
                .addComponent(btnThem, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(20, 20, 20)
                .addComponent(btnSua, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(1061, Short.MAX_VALUE))
        );
        panelButtonLayout.setVerticalGroup(
            panelButtonLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelButtonLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addGroup(panelButtonLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(btnSua, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnThem, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(21, 21, 21))
        );

        javax.swing.GroupLayout panelLeftBottomLayout = new javax.swing.GroupLayout(panelLeftBottom);
        panelLeftBottom.setLayout(panelLeftBottomLayout);
        panelLeftBottomLayout.setHorizontalGroup(
            panelLeftBottomLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panelSDT, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(panelLeftBottomLayout.createSequentialGroup()
                .addGroup(panelLeftBottomLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(panelCaLam, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(panelTen, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(panelLuong, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(panelButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        panelLeftBottomLayout.setVerticalGroup(
            panelLeftBottomLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelLeftBottomLayout.createSequentialGroup()
                .addGap(0, 0, 0)
                .addComponent(panelTen, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(panelCaLam, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(panelLuong, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(panelSDT, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(panelButton, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout panelLeftLayout = new javax.swing.GroupLayout(panelLeft);
        panelLeft.setLayout(panelLeftLayout);
        panelLeftLayout.setHorizontalGroup(
            panelLeftLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panelLeftTop, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(panelLeftBottom, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        panelLeftLayout.setVerticalGroup(
            panelLeftLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelLeftLayout.createSequentialGroup()
                .addComponent(panelLeftTop, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(panelLeftBottom, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        panelContent.add(panelLeft, java.awt.BorderLayout.CENTER);

        add(panelContent, java.awt.BorderLayout.CENTER);
        panelContent.add(panelLeft, java.awt.BorderLayout.CENTER);
        panelContent.add(panelRight, java.awt.BorderLayout.SOUTH);
    }// </editor-fold>//GEN-END:initComponents

    private void tableMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tableMouseClicked
        int row = table.getSelectedRow();
        txtTen.setText(tblModelEmp.getValueAt(row, 1).toString());
        String caLam = tblModelEmp.getValueAt(row, 2).toString();
        if (radio1.getText().equalsIgnoreCase(caLam)) {
            radio1.setSelected(true);
        } else if (radio2.getText().equalsIgnoreCase(caLam)) {
            radio2.setSelected(true);
        } else if (radio3.getText().equalsIgnoreCase(caLam)) {
            radio3.setSelected(true);
        }
        txtLuong.setText(tblModelEmp.getValueAt(row, 3).toString());
        txtSDT.setText(tblModelEmp.getValueAt(row, 4).toString());
        txtDiaChi.setText(tblModelEmp.getValueAt(row, 5).toString());
        String phanQuyen = tblModelEmp.getValueAt(row, 6).toString();
        if (radioQL.getText().equalsIgnoreCase(phanQuyen)) {
            radioQL.setSelected(true);
        } else if (radioNV.getText().equalsIgnoreCase(phanQuyen)) {
            radioNV.setSelected(true);
        }
    }//GEN-LAST:event_tableMouseClicked

    private void scrollMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_scrollMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_scrollMouseClicked

    private void txtTimActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtTimActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtTimActionPerformed

    private void btnSearchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSearchActionPerformed
        // TODO add your handling code here:
        tblModelEmp.setRowCount(0);
        String txtFind = txtTim.getText().trim();
        Employee emp = de.findById(txtFind);

        if (emp != null) {
            tblModelEmp.addRow(new Object[]{emp.getEmployeeID(), emp.getName(), emp.getShift(), emp.getSalary(), emp.getPhoneNumber(), emp.getAddress(), emp.getRole()});
            int countCus = de.findAll().size();
            if (countCus > 0) {
                lblCountNV.setText(countCus + "");
            } else {
                lblCountNV.setText("0");
            }
        } else {
            JOptionPane.showMessageDialog(this, "Không tìm thấy !");
            loadData();
        }
    }//GEN-LAST:event_btnSearchActionPerformed

    private void txtSDTActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtSDTActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtSDTActionPerformed

    private void radio2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_radio2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_radio2ActionPerformed

    private void txtDiaChiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtDiaChiActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtDiaChiActionPerformed

    private void txtLuongActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtLuongActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtLuongActionPerformed
    private Employee revertEmployee() {
        String ten = txtTen.getText().trim();
        String luong = txtLuong.getText().trim();
        Double luongg = Double.parseDouble(luong);
        int caLam = 0;

        if (radio1.isSelected()) {
            caLam = 1;
        } else if (radio2.isSelected()) {
            caLam = 2;
        } else if (radio3.isSelected()) {
            caLam = 3;
        }

        String sdt = txtSDT.getText().trim();
        String diaChi = txtDiaChi.getText().trim();

        String phanQuyen = "";
        if (radioQL.isSelected()) {
            phanQuyen = radioQL.getText();
        } else {
            phanQuyen = radioNV.getText();
        }

        return new Employee(ten, luongg, caLam, sdt, diaChi, phanQuyen);
    }
    private void btnThemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnThemActionPerformed
        // TODO add your handling code here:
        if (Validata()) {
            Employee emp = revertEmployee();
            if (de.insert(emp)) {
                JOptionPane.showMessageDialog(this, "Thêm thành công!");
                tblModelEmp.addRow(new Object[]{emp.getEmployeeID(), emp.getName(), emp.getShift(), emp.getSalary(), emp.getPhoneNumber(), emp.getAddress(), emp.getRole()});
                int countCus = de.findAll().size();
                if (countCus > 0) {
                    lblCountNV.setText(countCus + "");
                } else {
                    lblCountNV.setText("0");
                }
                de.insert(emp);
            } else {
                JOptionPane.showMessageDialog(null, "Nhân viên đã tồn tại này đã tồn tại", "Lỗi", JOptionPane.ERROR_MESSAGE);
            }
        }
    }//GEN-LAST:event_btnThemActionPerformed
    boolean Validata() {

        String ten = txtTen.getText().trim();
        if (ten.equals("")) {
            errorTen.setForeground(Color.RED);
            errorTen.setText("Tên không hợp lệ");
            return false;
        } else {
            errorTen.setForeground(Color.GREEN);
            errorTen.setText(" V ");
        }
        String luongg = txtLuong.getText().trim();
        double luong = 0;
        if (!luongg.matches("[0-9]+")) {
            errorLuong.setForeground(Color.RED);
            errorLuong.setText("Lương phải là một số hợp lệ");
            return false;
        } else {
            luong = Double.parseDouble(txtLuong.getText().trim());
            errorLuong.setForeground(Color.GREEN);
            errorLuong.setText(" V ");
        }
        int caLam = 0;

        if (radio1.isSelected()) {
            caLam = Integer.parseInt(radio1.getText());
        } else if (radio2.isSelected()) {
            caLam = Integer.parseInt(radio2.getText());
        } else if (radio3.isSelected()) {
            caLam = Integer.parseInt(radio3.getText());
        }

        String sdt = txtSDT.getText().trim();
        if (!sdt.matches("[0-9]+")) {
            errorSDT.setForeground(Color.RED);
            errorSDT.setText("SDT không hợp lệ");
            return false;
        } else {
            errorSDT.setForeground(Color.GREEN);
            errorSDT.setText(" V ");
        }
        String diaChi = txtDiaChi.getText().trim();
        if (diaChi.equals("")) {
            errorDiaChi.setForeground(Color.RED);
            errorDiaChi.setText("Địa chỉ không được để trống ");
            return false;
        } else {
            errorDiaChi.setForeground(Color.GREEN);
            errorDiaChi.setText(" V ");
        }
        String phanQuyen = "";
        if (radioQL.isSelected()) {
            phanQuyen = radioQL.getText();
        } else {
            phanQuyen = radioNV.getText();
        }
        return true;

    }
    private void btnSuaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSuaActionPerformed
        // TODO add your handling code here:
        if (Validata()) {
            int row = table.getSelectedRow();
            String empID = tblModelEmp.getValueAt(row, 0).toString();
            String newName = txtTen.getText().trim();
            double newLuong = Double.parseDouble(txtLuong.getText().trim());
            int newCaLam = 0;
            if (radio1.isSelected()) {
                newCaLam = Integer.parseInt(radio1.getText());
            } else if (radio2.isSelected()) {
                newCaLam = Integer.parseInt(radio2.getText());
            } else if (radio3.isSelected()) {
                newCaLam = Integer.parseInt(radio3.getText());
            }
            String newSDT = txtSDT.getText().trim();
            String newDiaChi = txtDiaChi.getText().trim();
            String newPhanQuyen = "";
            if (radioQL.isSelected()) {
                newPhanQuyen = radioQL.getText();
            } else {
                newPhanQuyen = radioNV.getText();
            }

            tblModelEmp.setValueAt(txtTen.getText(), row, 1);
            if (radio1.isSelected()) {
                tblModelEmp.setValueAt(radio1.getText(), row, 2);
            } else if (radio2.isSelected()) {
                tblModelEmp.setValueAt(radio2.getText(), row, 2);
            } else if (radio3.isSelected()) {
                tblModelEmp.setValueAt(radio3.getText(), row, 2);
            }
            tblModelEmp.setValueAt(txtLuong.getText(), row, 3);
            tblModelEmp.setValueAt(txtSDT.getText(), row, 4);
            tblModelEmp.setValueAt(txtDiaChi.getText(), row, 5);
            if (radioQL.isSelected()) {
                tblModelEmp.setValueAt(radioQL.getText(), row, 6);
            } else if (radioNV.isSelected()) {
                tblModelEmp.setValueAt(radioNV.getText(), row, 6);
            }
            Employee e = de.findById(empID);
            e.setName(newName);
            e.setShift(newCaLam);
            e.setSalary(newLuong);
            e.setPhoneNumber(newSDT);
            e.setAddress(newDiaChi);
            e.setRole(newPhanQuyen);
            //Employee newEmployees = new Employee(empID, newName, newLuong, newCaLam, newSDT, newDiaChi, newPhanQuyen);
            de.update(e);
            JOptionPane.showMessageDialog(this, "Sửa thành công!");
        }
    }//GEN-LAST:event_btnSuaActionPerformed
//    boolean ValidataEdit() {
//        int row = table.getSelectedRow();
//        String newName = txtTen.getText().trim();
//        if (newName.equals("")) {
//            errorTen.setForeground(Color.RED);
//            errorTen.setText("Tên không hợp lệ");
//            return false;
//        } else {
//            errorTen.setForeground(Color.GREEN);
//            errorTen.setText(" V ");
//        }
//        String luongg = txtLuong.getText().trim();
//        double newLuong = 0;
//        if (luongg.equals("")) {
//            errorLuong.setForeground(Color.RED);
//            errorLuong.setText("Lương phải là một số hợp lệ");
//            return false;
//        } else {
//            newLuong = Double.parseDouble(txtLuong.getText().trim());
//            errorLuong.setForeground(Color.GREEN);
//            errorLuong.setText(" V ");
//        }
//        int newCaLam = 0;
//        if (radio1.isSelected()) {
//            newCaLam = Integer.parseInt(radio1.getText());
//        } else if (radio2.isSelected()) {
//            newCaLam = Integer.parseInt(radio2.getText());
//        } else if (radio3.isSelected()) {
//            newCaLam = Integer.parseInt(radio3.getText());
//        }
//
//        String newSDT = txtSDT.getText().trim();
//        if (newSDT.equals("")) {
//            errorSDT.setForeground(Color.RED);
//            errorSDT.setText("SDT không hợp lệ");
//            return false;
//        } else {
//            errorSDT.setForeground(Color.GREEN);
//            errorSDT.setText(" V ");
//        }
//        String newDiaChi = txtDiaChi.getText().trim();
//        if (newDiaChi.equals("")) {
//            errorDiaChi.setForeground(Color.RED);
//            errorDiaChi.setText("Địa chỉ không được để trống ");
//            return false;
//        } else {
//            errorDiaChi.setForeground(Color.GREEN);
//            errorDiaChi.setText(" V ");
//        }
//        String newPhanQuyen = "";
//        if (radioQL.isSelected()) {
//            newPhanQuyen = radioQL.getText();
//        } else {
//            newPhanQuyen = radioNV.getText();
//        }
//        String empID = tblModelEmp.getValueAt(row, 0).toString();
//        Employee e = de.findById(empID);
//
//        e.setName(newName);
//        e.setShift(newCaLam);
//        e.setSalary(newLuong);
//        e.setPhoneNumber(newSDT);
//        e.setAddress(newDiaChi);
//        e.setRole(newPhanQuyen);
//
//        tblModelEmp.setValueAt(newName, row, 1);
//        tblModelEmp.setValueAt(newCaLam, row, 2);
//        tblModelEmp.setValueAt(newLuong, row, 3);
//        tblModelEmp.setValueAt(newSDT, row, 4);
//        tblModelEmp.setValueAt(newDiaChi, row, 5);
//        tblModelEmp.setValueAt(newPhanQuyen, row, 6);
//
//        de.update(e);
//        return true;
//
//    }

    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ManageEmployees.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ManageEmployees.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ManageEmployees.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ManageEmployees.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ManageEmployees().setVisible(true);
            }
        });
    }

    public void loadData() {
        radio1.setSelected(true);
        radioQL.setSelected(true);
//        if(listTopEmp.size() > 0){
//            lblCountNV.setText(listTopEmp.size()+"");
//        } else{
//            lblCountNV.setText("0");
//        }
        List<Employee> listTopEmp = de.getListTopEmp();
        for (Employee emp : listTopEmp) {
            tblModelEmp.addRow(new Object[]{emp.getEmployeeID(), emp.getName(), emp.getShift(), emp.getSalary(), emp.getPhoneNumber(), emp.getAddress(), emp.getRole()});
            int countCus = de.findAll().size();
            if (countCus > 0) {
                lblCountNV.setText(countCus + "");
            } else {
                lblCountNV.setText("0");
            }
        }
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnSearch;
    private javax.swing.JButton btnSua;
    private javax.swing.JButton btnThem;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.ButtonGroup buttonGroup2;
    private javax.swing.JLabel errorDiaChi;
    private javax.swing.JLabel errorLuong;
    private javax.swing.JLabel errorSDT;
    private javax.swing.JLabel errorTen;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel lblCaLam;
    private javax.swing.JLabel lblCountNV;
    private javax.swing.JLabel lblDiaChi;
    private javax.swing.JLabel lblIconAccont;
    private javax.swing.JLabel lblLuong2;
    private javax.swing.JLabel lblQuyen;
    private javax.swing.JLabel lblSDT;
    private javax.swing.JLabel lblTen;
    private javax.swing.JLabel lblTim;
    private javax.swing.JPanel panelButton;
    private javax.swing.JPanel panelCaLam;
    private javax.swing.JPanel panelContent;
    private javax.swing.JPanel panelCoutNV;
    private javax.swing.JPanel panelFind;
    private javax.swing.JPanel panelIconAccount;
    private javax.swing.JPanel panelLeft;
    private javax.swing.JPanel panelLeftBottom;
    private javax.swing.JPanel panelLeftTop;
    private javax.swing.JPanel panelLuong;
    private javax.swing.JPanel panelRight;
    private javax.swing.JPanel panelSDT;
    private javax.swing.JPanel panelTen;
    private javax.swing.JRadioButton radio1;
    private javax.swing.JRadioButton radio2;
    private javax.swing.JRadioButton radio3;
    private javax.swing.JRadioButton radioNV;
    private javax.swing.JRadioButton radioQL;
    private javax.swing.JScrollPane scroll;
    private javax.swing.JTable table;
    private javax.swing.JTextField txtDiaChi;
    private javax.swing.JTextField txtLuong;
    private javax.swing.JTextField txtSDT;
    private javax.swing.JTextField txtTen;
    private javax.swing.JTextField txtTim;
    // End of variables declaration//GEN-END:variables
}
