/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package gui;

import gui.custom.CustomRectangularButton;
import gui.custom.CustomScrollBarUI;
import db.*;
import entities.*;
import java.awt.Color;
import java.awt.Component;
import java.awt.Dimension;
import java.awt.Font;
import javax.swing.JLabel;
import javax.swing.JOptionPane;
import javax.swing.JTable;
import javax.swing.SwingConstants;
import javax.swing.table.DefaultTableCellRenderer;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableColumn;
import javax.swing.table.TableColumnModel;
import java.util.List;
import javax.swing.BorderFactory;
import dao.*;
import javax.swing.JScrollPane;

/**
 *
 * @author ADMIN
 */
public class ManageCategories extends javax.swing.JPanel {

    private List<Category> listTopCate;
    private DAOCategory dc = new DAOCategory();
    private DefaultTableModel tblModelCate;
    private int row;

    /**
     * Creates new form ManageCate
     */
    public ManageCategories() {
        initComponents();
        loadData();
        int countCus = dc.findAll().size();
        if (countCus > 0) {
            lblCountDM.setText(countCus + "");
        } else {
            lblCountDM.setText("0");
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panelContent = new javax.swing.JPanel();
        panelLeft = new javax.swing.JPanel();
        panelLeftBottom = new javax.swing.JPanel();
        panelTen = new javax.swing.JPanel();
        lblTenDM = new javax.swing.JLabel();
        txtDanhMuc = new javax.swing.JTextField();
        panelBtn = new javax.swing.JPanel();
        btnThem = new javax.swing.JButton();
        btnSua = new javax.swing.JButton();
        panelMoTa = new javax.swing.JPanel();
        lblMoTa = new javax.swing.JLabel();
        txtMoTa = new javax.swing.JTextField();
        panelErrorMoTa = new javax.swing.JPanel();
        errorMoTa = new javax.swing.JLabel();
        panelErrorTen = new javax.swing.JPanel();
        errorTen = new javax.swing.JLabel();
        panelLeftTop = new javax.swing.JPanel();
        panelIconAccount = new javax.swing.JPanel();
        lblIconAccont = new javax.swing.JLabel();
        panelFind = new javax.swing.JPanel();
        lblTim = new javax.swing.JLabel();
        txtTim = new javax.swing.JTextField();
        btnSearch = new CustomRectangularButton(new Color[] {Color.WHITE, new Color(102, 44, 33), new Color(118, 68, 52)});
        panelRight = new javax.swing.JPanel();
        scroll = new javax.swing.JScrollPane();
        table = new javax.swing.JTable();
        jPanel1 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        lblCountDM = new javax.swing.JLabel();

        panelContent.setLayout(new java.awt.BorderLayout());

        panelLeft.setBackground(new java.awt.Color(211, 180, 160));

        panelLeftBottom.setBackground(new java.awt.Color(211, 180, 160));
        panelLeftBottom.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "THÔNG TIN", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Segoe UI", 0, 18))); // NOI18N

        panelTen.setBackground(new java.awt.Color(211, 180, 160));

        lblTenDM.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        lblTenDM.setText("Tên danh mục:");

        txtDanhMuc.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 10, 1, 1));
        txtDanhMuc.setName(""); // NOI18N
        txtDanhMuc.setPreferredSize(new java.awt.Dimension(64, 25));
        txtDanhMuc.setSelectionColor(new java.awt.Color(102, 44, 33));

        javax.swing.GroupLayout panelTenLayout = new javax.swing.GroupLayout(panelTen);
        panelTen.setLayout(panelTenLayout);
        panelTenLayout.setHorizontalGroup(
            panelTenLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelTenLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(lblTenDM, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(21, 21, 21)
                .addComponent(txtDanhMuc, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        panelTenLayout.setVerticalGroup(
            panelTenLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelTenLayout.createSequentialGroup()
                .addGap(0, 0, 0)
                .addGroup(panelTenLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblTenDM)
                    .addComponent(txtDanhMuc, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(0, 0, Short.MAX_VALUE))
        );

        panelBtn.setBackground(new java.awt.Color(211, 180, 160));

        btnThem.setBackground(new java.awt.Color(102, 44, 33));
        btnThem.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/icons8-plus-30.png"))); // NOI18N
        btnThem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnThemActionPerformed(evt);
            }
        });

        btnSua.setBackground(new java.awt.Color(102, 44, 33));
        btnSua.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/icons8-edit-30 .png"))); // NOI18N
        btnSua.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSuaActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout panelBtnLayout = new javax.swing.GroupLayout(panelBtn);
        panelBtn.setLayout(panelBtnLayout);
        panelBtnLayout.setHorizontalGroup(
            panelBtnLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelBtnLayout.createSequentialGroup()
                .addContainerGap(744, Short.MAX_VALUE)
                .addComponent(btnThem, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(50, 50, 50)
                .addComponent(btnSua, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(744, Short.MAX_VALUE))
        );
        panelBtnLayout.setVerticalGroup(
            panelBtnLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelBtnLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(panelBtnLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnSua, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnThem, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(21, 21, 21))
        );

        panelMoTa.setBackground(new java.awt.Color(211, 180, 160));

        lblMoTa.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        lblMoTa.setText("Mô tả");

        txtMoTa.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 10, 1, 1));
        txtMoTa.setSelectionColor(new java.awt.Color(102, 44, 33));

        javax.swing.GroupLayout panelMoTaLayout = new javax.swing.GroupLayout(panelMoTa);
        panelMoTa.setLayout(panelMoTaLayout);
        panelMoTaLayout.setHorizontalGroup(
            panelMoTaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelMoTaLayout.createSequentialGroup()
                .addContainerGap(648, Short.MAX_VALUE)
                .addComponent(lblMoTa, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(28, 28, 28)
                .addComponent(txtMoTa, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(648, Short.MAX_VALUE))
        );
        panelMoTaLayout.setVerticalGroup(
            panelMoTaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelMoTaLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panelMoTaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(panelMoTaLayout.createSequentialGroup()
                        .addComponent(txtMoTa, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(1, 1, 1))
                    .addComponent(lblMoTa))
                .addContainerGap(7, Short.MAX_VALUE))
        );

        panelErrorMoTa.setBackground(new java.awt.Color(211, 180, 160));

        errorMoTa.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        errorMoTa.setPreferredSize(new java.awt.Dimension(64, 25));

        javax.swing.GroupLayout panelErrorMoTaLayout = new javax.swing.GroupLayout(panelErrorMoTa);
        panelErrorMoTa.setLayout(panelErrorMoTaLayout);
        panelErrorMoTaLayout.setHorizontalGroup(
            panelErrorMoTaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelErrorMoTaLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(errorMoTa, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(577, 577, 577))
        );
        panelErrorMoTaLayout.setVerticalGroup(
            panelErrorMoTaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelErrorMoTaLayout.createSequentialGroup()
                .addComponent(errorMoTa, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 6, Short.MAX_VALUE))
        );

        panelErrorTen.setBackground(new java.awt.Color(211, 180, 160));
        panelErrorTen.setPreferredSize(new java.awt.Dimension(832, 40));

        errorTen.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N

        javax.swing.GroupLayout panelErrorTenLayout = new javax.swing.GroupLayout(panelErrorTen);
        panelErrorTen.setLayout(panelErrorTenLayout);
        panelErrorTenLayout.setHorizontalGroup(
            panelErrorTenLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelErrorTenLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(errorTen, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(626, 626, 626))
        );
        panelErrorTenLayout.setVerticalGroup(
            panelErrorTenLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelErrorTenLayout.createSequentialGroup()
                .addGap(10, 10, 10)
                .addComponent(errorTen, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(8, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout panelLeftBottomLayout = new javax.swing.GroupLayout(panelLeftBottom);
        panelLeftBottom.setLayout(panelLeftBottomLayout);
        panelLeftBottomLayout.setHorizontalGroup(
            panelLeftBottomLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panelTen, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(panelErrorTen, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 1624, Short.MAX_VALUE)
            .addComponent(panelBtn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(panelErrorMoTa, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(panelLeftBottomLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(panelMoTa, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        panelLeftBottomLayout.setVerticalGroup(
            panelLeftBottomLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelLeftBottomLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(panelTen, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(panelErrorTen, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(67, 67, 67)
                .addComponent(panelErrorMoTa, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(panelBtn, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
            .addGroup(panelLeftBottomLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(panelLeftBottomLayout.createSequentialGroup()
                    .addGap(96, 96, 96)
                    .addComponent(panelMoTa, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(358, Short.MAX_VALUE)))
        );

        panelLeftTop.setBackground(new java.awt.Color(211, 180, 160));

        panelIconAccount.setBackground(new java.awt.Color(211, 180, 160));

        lblIconAccont.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/icons8-diversity-100.png"))); // NOI18N

        javax.swing.GroupLayout panelIconAccountLayout = new javax.swing.GroupLayout(panelIconAccount);
        panelIconAccount.setLayout(panelIconAccountLayout);
        panelIconAccountLayout.setHorizontalGroup(
            panelIconAccountLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelIconAccountLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(lblIconAccont)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        panelIconAccountLayout.setVerticalGroup(
            panelIconAccountLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelIconAccountLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblIconAccont, javax.swing.GroupLayout.PREFERRED_SIZE, 89, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        panelFind.setBackground(new java.awt.Color(211, 180, 160));

        lblTim.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        lblTim.setText("Nhập mã danh mục cần tìm");

        txtTim.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 10, 1, 1));
        txtTim.setPreferredSize(new java.awt.Dimension(64, 25));
        txtTim.setSelectionColor(new java.awt.Color(102, 44, 33));
        txtTim.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtTimActionPerformed(evt);
            }
        });

        btnSearch.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/icons8-search-24.png"))); // NOI18N
        btnSearch.setFocusPainted(false);
        btnSearch.setMargin(new java.awt.Insets(0, 0, 0, 0));
        btnSearch.setOpaque(true);
        btnSearch.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSearchActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout panelFindLayout = new javax.swing.GroupLayout(panelFind);
        panelFind.setLayout(panelFindLayout);
        panelFindLayout.setHorizontalGroup(
            panelFindLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelFindLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(lblTim, javax.swing.GroupLayout.PREFERRED_SIZE, 239, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtTim, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnSearch, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        panelFindLayout.setVerticalGroup(
            panelFindLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelFindLayout.createSequentialGroup()
                .addContainerGap(12, Short.MAX_VALUE)
                .addGroup(panelFindLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnSearch, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelFindLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(lblTim)
                        .addComponent(txtTim, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );

        javax.swing.GroupLayout panelLeftTopLayout = new javax.swing.GroupLayout(panelLeftTop);
        panelLeftTop.setLayout(panelLeftTopLayout);
        panelLeftTopLayout.setHorizontalGroup(
            panelLeftTopLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelLeftTopLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panelLeftTopLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(panelIconAccount, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(panelFind, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        panelLeftTopLayout.setVerticalGroup(
            panelLeftTopLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelLeftTopLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(panelIconAccount, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(panelFind, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout panelLeftLayout = new javax.swing.GroupLayout(panelLeft);
        panelLeft.setLayout(panelLeftLayout);
        panelLeftLayout.setHorizontalGroup(
            panelLeftLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panelLeftTop, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(panelLeftBottom, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        panelLeftLayout.setVerticalGroup(
            panelLeftLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelLeftLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(panelLeftTop, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(panelLeftBottom, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        panelContent.add(panelLeft, java.awt.BorderLayout.CENTER);

        panelRight.setBackground(new java.awt.Color(211, 180, 160));

        scroll.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                scrollMouseClicked(evt);
            }
        });

        String[] header = {"Mã danh mục", "Tên danh mục", "Mô tả"};
        tblModelCate = new DefaultTableModel(header, 0) {
            boolean[] canEdit = new boolean[]{
                false, false, false
            };

            @Override
            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit[columnIndex];
            }
        };
        table.setModel(tblModelCate);
        table.setFont(new java.awt.Font("Segoe UI", 0, 16));
        table.getTableHeader().setResizingAllowed(false);
        for (int i = 0; i < table.getColumnCount(); i++) {
            table.getColumnModel().getColumn(i).setResizable(false);
        }
        table.getTableHeader().setPreferredSize(new Dimension(table.getColumnModel().getTotalColumnWidth(), 50));
        table.getTableHeader().setBorder(BorderFactory.createMatteBorder(0, 0, 1, 0, new Color(102, 44, 33)));
        table.getTableHeader().setDefaultRenderer(new javax.swing.table.DefaultTableCellRenderer() {
            @Override
            public Component getTableCellRendererComponent(JTable table, Object value, boolean isSelected, boolean hasFocus, int row, int column) {
                JLabel label = (JLabel) super.getTableCellRendererComponent(table, value, isSelected, hasFocus, row, column);
                label.setBackground(new Color(235, 228, 226));  // Thiết lập màu nền
                label.setOpaque(true);  // Đảm bảo màu nền được áp dụng
                label.setFont(new Font("Segoe UI", Font.BOLD, 17));
                label.setHorizontalAlignment(SwingConstants.CENTER);  // Căn giữa văn bản
                return label;
            }
        });

        // Thiết lập DefaultTableCellRenderer để căn giữa
        DefaultTableCellRenderer centerRenderer = new DefaultTableCellRenderer();
        centerRenderer.setHorizontalAlignment(SwingConstants.CENTER);

        // Áp dụng renderer này cho tất cả các cột
        for (int i = 0; i < table.getColumnCount(); i++) {
            TableColumn column = table.getColumnModel().getColumn(i);
            column.setCellRenderer(centerRenderer);
        }

        table.setRowHeight(50);

        table.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_INTERVAL_SELECTION);

        table.getTableHeader().setReorderingAllowed(false);

        TableColumnModel columnModel = table.getColumnModel();
        TableColumn col0 = columnModel.getColumn(0);
        TableColumn col1 = columnModel.getColumn(1);
        TableColumn col2 = columnModel.getColumn(2);

        col0.setPreferredWidth(30);
        col1.setPreferredWidth(120);
        col2.setPreferredWidth(20);
        table.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);

        table.getTableHeader().setResizingAllowed(false);
        for (int i = 0; i < table.getColumnCount(); i++) {
            table.getColumnModel().getColumn(i).setResizable(false);
        }
        table.setModel(tblModelCate);
        table.setSelectionBackground(new java.awt.Color(102, 44, 33));
        table.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tableMouseClicked(evt);
            }
        });
        scroll.setViewportView(table);
        scroll.getViewport().setBackground(new Color(235, 228, 226));
        scroll.getVerticalScrollBar().setUI(new CustomScrollBarUI());

        jPanel1.setBackground(new java.awt.Color(211, 180, 160));

        jLabel4.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel4.setText("Tổng số danh mục: ");

        lblCountDM.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 168, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblCountDM, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(lblCountDM, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, 57, Short.MAX_VALUE)
                .addContainerGap())
        );

        javax.swing.GroupLayout panelRightLayout = new javax.swing.GroupLayout(panelRight);
        panelRight.setLayout(panelRightLayout);
        panelRightLayout.setHorizontalGroup(
            panelRightLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(scroll, javax.swing.GroupLayout.DEFAULT_SIZE, 1634, Short.MAX_VALUE)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        panelRightLayout.setVerticalGroup(
            panelRightLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelRightLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(scroll, javax.swing.GroupLayout.PREFERRED_SIZE, 363, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(20, 20, 20))
        );

        panelContent.add(panelRight, java.awt.BorderLayout.PAGE_START);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1634, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(panelContent, javax.swing.GroupLayout.PREFERRED_SIZE, 1634, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 956, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(panelContent, javax.swing.GroupLayout.PREFERRED_SIZE, 956, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );

        panelContent.add(panelLeft, java.awt.BorderLayout.CENTER);
        panelContent.add(panelRight, java.awt.BorderLayout.SOUTH);
    }// </editor-fold>//GEN-END:initComponents
private Category revertCategory() {
        String ten = txtDanhMuc.getText().trim();
        String moTa = txtMoTa.getText().trim();
        return new Category(ten, moTa);
    }
    private void btnThemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnThemActionPerformed
        // TODO add your handling code here:
        
        if (Validata()) {
            Category cate = revertCategory();
            if (dc.insert(cate)) {
                JOptionPane.showMessageDialog(this, "Thêm thành công!");
                tblModelCate.addRow(new Object[]{cate.getCategoryID(), cate.getName(), cate.getDescription()});
                int countCus = dc.findAll().size();
                if (countCus > 0) {
                    lblCountDM.setText(countCus + "");
                } else {
                    lblCountDM.setText("0");
                }
//                dc.insert(cate);
                gui.CreateOrder.tabCat.add(cate.getName(), new JScrollPane());
            } else {
                JOptionPane.showMessageDialog(null, "Danh mục đã tồn tại này đã tồn tại", "Lỗi", JOptionPane.ERROR_MESSAGE);
            }

        }

    }//GEN-LAST:event_btnThemActionPerformed
    boolean Validata() {
        String name = txtDanhMuc.getText().trim();
        if (name.equals("")) {
            errorTen.setForeground(Color.RED);
            errorTen.setText("Tên không hợp lệ");
            return false;
        } else {
            errorTen.setForeground(Color.GREEN);
            errorTen.setText(" V ");
        }
        String moTa = txtMoTa.getText().trim();
        if (moTa.equals("")) {
            errorMoTa.setForeground(Color.RED);
            errorMoTa.setText("Mô tả không được để trống !");
            return false;
        } else {
            errorMoTa.setForeground(Color.GREEN);
            errorMoTa.setText(" V ");
        }
        return true;

    }
    private void btnSuaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSuaActionPerformed
        // TODO add your handling code here:
        if (Validata()) {
            int row = table.getSelectedRow();
            String name = txtDanhMuc.getText();
            String desc = txtMoTa.getText();

            String cateID = tblModelCate.getValueAt(row, 0).toString();

            tblModelCate.setValueAt(txtDanhMuc.getText(), row, 1);
            tblModelCate.setValueAt(txtMoTa.getText(), row, 2);

            Category newCategory = new Category(cateID, name, desc);
            dc.update(newCategory);
            String newCateID = newCategory.getCategoryID();
            int indexTabCat = Integer.parseInt(newCateID.substring(1, newCateID.length()));

            gui.CreateOrder.tabCat.setTitleAt(indexTabCat - 1, newCategory.getName());
            JOptionPane.showMessageDialog(this, "Sửa thành công!");
        }
    }//GEN-LAST:event_btnSuaActionPerformed

    private void txtTimActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtTimActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtTimActionPerformed

    private void btnSearchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSearchActionPerformed
        // TODO add your handling code here:
        tblModelCate.setRowCount(0);
        String txtFind = txtTim.getText().trim();
        Category cate = dc.findById(txtFind);

        if (cate != null) {
            tblModelCate.addRow(new Object[]{cate.getCategoryID(), cate.getName(), cate.getDescription()});
            int countCus = dc.findAll().size();
            if (countCus > 0) {
                lblCountDM.setText(countCus + "");
            } else {
                lblCountDM.setText("0");
            }
        } else {
            JOptionPane.showMessageDialog(this, "Không tìm thấy !");
            loadData();
        }
    }//GEN-LAST:event_btnSearchActionPerformed

    private void scrollMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_scrollMouseClicked
        // TODO add your handling code here:

    }//GEN-LAST:event_scrollMouseClicked

    private void tableMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tableMouseClicked
        // TODO add your handling code here:
        int row = table.getSelectedRow();
        txtDanhMuc.setText(tblModelCate.getValueAt(row, 1).toString());
        txtMoTa.setText(tblModelCate.getValueAt(row, 2).toString());
    }//GEN-LAST:event_tableMouseClicked

    public void loadData() {
        List<Category> listTopCate = dc.getListTopCate();
        for (Category cate : listTopCate) {
            tblModelCate.addRow(new Object[]{cate.getCategoryID(), cate.getName(), cate.getDescription()});
            int countCus = dc.findAll().size();
            if (countCus > 0) {
                lblCountDM.setText(countCus + "");
            } else {
                lblCountDM.setText("0");
            }
        }
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnSearch;
    private javax.swing.JButton btnSua;
    private javax.swing.JButton btnThem;
    private javax.swing.JLabel errorMoTa;
    private javax.swing.JLabel errorTen;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel lblCountDM;
    private javax.swing.JLabel lblIconAccont;
    private javax.swing.JLabel lblMoTa;
    private javax.swing.JLabel lblTenDM;
    private javax.swing.JLabel lblTim;
    private javax.swing.JPanel panelBtn;
    private javax.swing.JPanel panelContent;
    private javax.swing.JPanel panelErrorMoTa;
    private javax.swing.JPanel panelErrorTen;
    private javax.swing.JPanel panelFind;
    private javax.swing.JPanel panelIconAccount;
    private javax.swing.JPanel panelLeft;
    private javax.swing.JPanel panelLeftBottom;
    private javax.swing.JPanel panelLeftTop;
    private javax.swing.JPanel panelMoTa;
    private javax.swing.JPanel panelRight;
    private javax.swing.JPanel panelTen;
    private javax.swing.JScrollPane scroll;
    private javax.swing.JTable table;
    private javax.swing.JTextField txtDanhMuc;
    private javax.swing.JTextField txtMoTa;
    private javax.swing.JTextField txtTim;
    // End of variables declaration//GEN-END:variables
}
