/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package gui;

import gui.custom.CustomScrollBarUI;
import dao.*;
import entities.*;
import java.awt.*;
import java.awt.image.BufferedImage;
import java.io.File;
import java.io.IOException;
import java.nio.file.Files;
import java.nio.file.StandardCopyOption;
import java.util.List;
import java.time.LocalDateTime;
import javax.imageio.ImageIO;
import javax.swing.ImageIcon;
import javax.swing.JFileChooser;
import javax.swing.JLabel;
import javax.swing.JOptionPane;
import javax.swing.JTable;
import javax.swing.SwingConstants;
import javax.swing.filechooser.FileNameExtensionFilter;
import javax.swing.table.DefaultTableCellRenderer;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableColumn;
import javax.swing.table.TableColumnModel;

/**
 *
 * @author ACER
 */
public class ManageBeverages extends javax.swing.JPanel {

    private DAOBeverage db = new DAOBeverage();
    private DAOCategory dc = new DAOCategory();
    private DAOOrderdetail dod = new DAOOrderdetail();
    private static DefaultTableModel tblModelBev;
    private int row;
    private String imgPathCut;

    /**
     * Creates new form ManageBev
     */
    public ManageBeverages() {
        initComponents();
        loadData();
        int countBev = db.findAll().size();
        if (countBev > 0) {
            txtTotal.setText(countBev + "");
        } else {
            txtTotal.setText("0");
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panelNorth = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jPanel1 = new javax.swing.JPanel();
        panelSearch = new javax.swing.JPanel();
        lblSearch = new javax.swing.JLabel();
        txtSearch = new javax.swing.JTextField();
        btnSearch = new javax.swing.JButton();
        jPanelimg = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        panelInfo = new javax.swing.JPanel();
        panelInfoLeft = new javax.swing.JPanel();
        panelNameCatBev = new javax.swing.JPanel();
        lblNameCatBev = new javax.swing.JLabel();
        //String options[] = {"Chọn loại nước uống", "C001", "C002", "C003", "C004", "C005"};
        cbbNameCatBev = new javax.swing.JComboBox<>();
        panelNameBev = new javax.swing.JPanel();
        lblNameBev = new javax.swing.JLabel();
        txtNameBev = new javax.swing.JTextField();
        errorNameBev = new javax.swing.JLabel();
        panelPriceBev = new javax.swing.JPanel();
        lblPriceBev = new javax.swing.JLabel();
        txtPriceBev = new javax.swing.JTextField();
        errorPriceBev = new javax.swing.JLabel();
        panelInfoRight = new javax.swing.JPanel();
        panelmgBev = new javax.swing.JPanel();
        btnImg = new javax.swing.JButton();
        lblImg = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        cbDiscontinued = new javax.swing.JCheckBox();
        Discontinued = new javax.swing.JLabel();
        panelButton = new javax.swing.JPanel();
        btnAdd = new javax.swing.JButton();
        btnUpdate = new javax.swing.JButton();
        panelCenter = new javax.swing.JPanel();
        scroll = new javax.swing.JScrollPane();
        tblBev = new javax.swing.JTable();
        panelSouth = new javax.swing.JPanel();
        panelTotal = new javax.swing.JPanel();
        lblTotal = new javax.swing.JLabel();
        txtTotal = new javax.swing.JLabel();

        setBackground(new java.awt.Color(210, 180, 160));
        setMaximumSize(new java.awt.Dimension(1000, 1000));
        setLayout(new java.awt.BorderLayout());

        panelNorth.setBackground(new java.awt.Color(210, 180, 160));
        panelNorth.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Segoe UI", 0, 24))); // NOI18N
        panelNorth.setMaximumSize(new java.awt.Dimension(1000, 1000));

        jPanel2.setBackground(new java.awt.Color(210, 180, 160));
        jPanel2.setMaximumSize(new java.awt.Dimension(800, 800));
        jPanel2.setLayout(new java.awt.BorderLayout());

        jPanel1.setBackground(new java.awt.Color(210, 180, 160));

        panelSearch.setBackground(new java.awt.Color(210, 180, 160));

        lblSearch.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        lblSearch.setText("Tìm kiếm");

        txtSearch.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtSearchActionPerformed(evt);
            }
        });

        btnSearch.setBackground(new java.awt.Color(102, 44, 33));
        btnSearch.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btnSearch.setForeground(new java.awt.Color(255, 255, 255));
        btnSearch.setText("Tìm");
        btnSearch.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSearchActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout panelSearchLayout = new javax.swing.GroupLayout(panelSearch);
        panelSearch.setLayout(panelSearchLayout);
        panelSearchLayout.setHorizontalGroup(
            panelSearchLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelSearchLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(lblSearch)
                .addGap(0, 0, 0)
                .addComponent(txtSearch, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(btnSearch)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        panelSearchLayout.setVerticalGroup(
            panelSearchLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelSearchLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addGroup(panelSearchLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(panelSearchLayout.createSequentialGroup()
                        .addGap(2, 2, 2)
                        .addComponent(btnSearch, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelSearchLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(lblSearch, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(txtSearch, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );

        jPanelimg.setBackground(new java.awt.Color(210, 180, 160));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/icons8-cafe-100.png"))); // NOI18N

        javax.swing.GroupLayout jPanelimgLayout = new javax.swing.GroupLayout(jPanelimg);
        jPanelimg.setLayout(jPanelimgLayout);
        jPanelimgLayout.setHorizontalGroup(
            jPanelimgLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelimgLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanelimgLayout.setVerticalGroup(
            jPanelimgLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelimgLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanelimg, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(182, Short.MAX_VALUE)
                .addComponent(panelSearch, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(183, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jPanelimg, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(5, 5, 5)
                .addComponent(panelSearch, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0))
        );

        jPanel2.add(jPanel1, java.awt.BorderLayout.NORTH);

        panelInfo.setBackground(new java.awt.Color(210, 180, 160));
        panelInfo.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        panelInfo.setLayout(new java.awt.BorderLayout());

        panelInfoLeft.setBackground(new java.awt.Color(210, 180, 160));

        panelNameCatBev.setBackground(new java.awt.Color(210, 180, 160));

        lblNameCatBev.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        lblNameCatBev.setText("Loại thức uống");

        cbbNameCatBev.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        cbbNameCatBev.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbbNameCatBevActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout panelNameCatBevLayout = new javax.swing.GroupLayout(panelNameCatBev);
        panelNameCatBev.setLayout(panelNameCatBevLayout);
        panelNameCatBevLayout.setHorizontalGroup(
            panelNameCatBevLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelNameCatBevLayout.createSequentialGroup()
                .addGap(94, 94, 94)
                .addComponent(lblNameCatBev, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(cbbNameCatBev, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(237, Short.MAX_VALUE))
        );
        panelNameCatBevLayout.setVerticalGroup(
            panelNameCatBevLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelNameCatBevLayout.createSequentialGroup()
                .addGap(10, 10, 10)
                .addGroup(panelNameCatBevLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cbbNameCatBev, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblNameCatBev, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(5, 5, 5))
        );

        cbbNameCatBev.setBackground(new Color(235, 228, 226));

        panelNameBev.setBackground(new java.awt.Color(210, 180, 160));

        lblNameBev.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        lblNameBev.setText("Tên thức uống");

        txtNameBev.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        txtNameBev.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtNameBevActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout panelNameBevLayout = new javax.swing.GroupLayout(panelNameBev);
        panelNameBev.setLayout(panelNameBevLayout);
        panelNameBevLayout.setHorizontalGroup(
            panelNameBevLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelNameBevLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(lblNameBev, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(txtNameBev, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(errorNameBev, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        panelNameBevLayout.setVerticalGroup(
            panelNameBevLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelNameBevLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addGroup(panelNameBevLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(errorNameBev, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(panelNameBevLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(txtNameBev, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(lblNameBev, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(0, 0, 0))
        );

        panelPriceBev.setBackground(new java.awt.Color(210, 180, 160));

        lblPriceBev.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        lblPriceBev.setText("Giá thức uống");

        txtPriceBev.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        txtPriceBev.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtPriceBevActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout panelPriceBevLayout = new javax.swing.GroupLayout(panelPriceBev);
        panelPriceBev.setLayout(panelPriceBevLayout);
        panelPriceBevLayout.setHorizontalGroup(
            panelPriceBevLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelPriceBevLayout.createSequentialGroup()
                .addContainerGap(93, Short.MAX_VALUE)
                .addComponent(lblPriceBev, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(txtPriceBev, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(errorPriceBev, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(94, Short.MAX_VALUE))
        );
        panelPriceBevLayout.setVerticalGroup(
            panelPriceBevLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(errorPriceBev, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addGroup(panelPriceBevLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                .addComponent(lblPriceBev, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addComponent(txtPriceBev, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        javax.swing.GroupLayout panelInfoLeftLayout = new javax.swing.GroupLayout(panelInfoLeft);
        panelInfoLeft.setLayout(panelInfoLeftLayout);
        panelInfoLeftLayout.setHorizontalGroup(
            panelInfoLeftLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panelPriceBev, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(panelNameBev, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelInfoLeftLayout.createSequentialGroup()
                .addComponent(panelNameCatBev, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        panelInfoLeftLayout.setVerticalGroup(
            panelInfoLeftLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelInfoLeftLayout.createSequentialGroup()
                .addComponent(panelNameCatBev, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(panelNameBev, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(5, 5, 5)
                .addComponent(panelPriceBev, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        panelInfo.add(panelInfoLeft, java.awt.BorderLayout.NORTH);

        panelInfoRight.setBackground(new java.awt.Color(210, 180, 160));

        panelmgBev.setBackground(new java.awt.Color(210, 180, 160));

        btnImg.setBackground(new java.awt.Color(102, 44, 33));
        btnImg.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btnImg.setForeground(new java.awt.Color(255, 255, 255));
        btnImg.setText("Choose File");
        btnImg.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnImgActionPerformed(evt);
            }
        });

        lblImg.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N

        jLabel2.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel2.setText("Hình ảnh");

        javax.swing.GroupLayout panelmgBevLayout = new javax.swing.GroupLayout(panelmgBev);
        panelmgBev.setLayout(panelmgBevLayout);
        panelmgBevLayout.setHorizontalGroup(
            panelmgBevLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelmgBevLayout.createSequentialGroup()
                .addGap(93, 93, 93)
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(btnImg)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblImg, javax.swing.GroupLayout.DEFAULT_SIZE, 81, Short.MAX_VALUE)
                .addContainerGap())
        );
        panelmgBevLayout.setVerticalGroup(
            panelmgBevLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelmgBevLayout.createSequentialGroup()
                .addGap(0, 0, 0)
                .addGroup(panelmgBevLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblImg, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(panelmgBevLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(btnImg)
                        .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addContainerGap())
        );

        lblPriceBev.setPreferredSize(lblNameCatBev.getPreferredSize());
        lblNameBev.setPreferredSize(lblNameCatBev.getPreferredSize());
        lblSearch.setPreferredSize(lblNameCatBev.getPreferredSize());

        jPanel3.setBackground(new java.awt.Color(210, 180, 160));

        cbDiscontinued.setBackground(new java.awt.Color(235, 228, 226));
        cbDiscontinued.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbDiscontinuedActionPerformed(evt);
            }
        });

        Discontinued.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        Discontinued.setText("Ngừng SX");

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(Discontinued)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(cbDiscontinued)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(3, 3, 3)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(Discontinued, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(cbDiscontinued, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout panelInfoRightLayout = new javax.swing.GroupLayout(panelInfoRight);
        panelInfoRight.setLayout(panelInfoRightLayout);
        panelInfoRightLayout.setHorizontalGroup(
            panelInfoRightLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelInfoRightLayout.createSequentialGroup()
                .addComponent(panelmgBev, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 259, Short.MAX_VALUE))
            .addGroup(panelInfoRightLayout.createSequentialGroup()
                .addGap(87, 87, 87)
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        panelInfoRightLayout.setVerticalGroup(
            panelInfoRightLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelInfoRightLayout.createSequentialGroup()
                .addGap(0, 0, 0)
                .addComponent(panelmgBev, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        panelInfo.add(panelInfoRight, java.awt.BorderLayout.CENTER);

        jPanel2.add(panelInfo, java.awt.BorderLayout.CENTER);

        panelButton.setBackground(new java.awt.Color(210, 180, 160));

        btnAdd.setBackground(new java.awt.Color(102, 44, 33));
        btnAdd.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/icons8-plus-30.png"))); // NOI18N
        btnAdd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAddActionPerformed(evt);
            }
        });
        panelButton.add(btnAdd);

        btnUpdate.setBackground(new java.awt.Color(102, 44, 33));
        btnUpdate.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/icons8-edit-30 .png"))); // NOI18N
        btnUpdate.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        btnUpdate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnUpdateActionPerformed(evt);
            }
        });
        panelButton.add(btnUpdate);

        jPanel2.add(panelButton, java.awt.BorderLayout.SOUTH);

        javax.swing.GroupLayout panelNorthLayout = new javax.swing.GroupLayout(panelNorth);
        panelNorth.setLayout(panelNorthLayout);
        panelNorthLayout.setHorizontalGroup(
            panelNorthLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelNorthLayout.createSequentialGroup()
                .addContainerGap(34, Short.MAX_VALUE)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, 689, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(102, Short.MAX_VALUE))
        );
        panelNorthLayout.setVerticalGroup(
            panelNorthLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        add(panelNorth, java.awt.BorderLayout.NORTH);

        panelCenter.setBackground(new java.awt.Color(210, 180, 160));
        panelCenter.setForeground(new java.awt.Color(255, 255, 255));
        panelCenter.setLayout(new java.awt.BorderLayout());

        scroll.setBackground(new java.awt.Color(255, 255, 255));
        scroll.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));

        String[] header = {"Loại thức uống", "Mã thức uống", "Tên thức uống", "Giá thức uống", "Ngừng sản xuất", "Image"};
        tblModelBev = new DefaultTableModel(header, 0) {
            boolean[] canEdit = new boolean[]{
                false, false, false, false, false
            };

            @Override
            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit[columnIndex];
            }
        };
        tblBev.setModel(tblModelBev);
        tblBev.setFont(new java.awt.Font("Segoe UI", 0, 16));
        tblBev.getTableHeader().setResizingAllowed(false);
        for (int i = 0; i < tblBev.getColumnCount(); i++) {
            tblBev.getColumnModel().getColumn(i).setResizable(false);
        }
        tblBev.getTableHeader().setPreferredSize(new Dimension(tblBev.getColumnModel().getTotalColumnWidth(), 50));
        tblBev.getTableHeader().setDefaultRenderer(new javax.swing.table.DefaultTableCellRenderer() {
            @Override
            public Component getTableCellRendererComponent(JTable table, Object value, boolean isSelected, boolean hasFocus, int row, int column) {
                JLabel label = (JLabel) super.getTableCellRendererComponent(table, value, isSelected, hasFocus, row, column);
                label.setBackground(new Color(235,228,226)); // Thiết lập màu nền
                label.setOpaque(true);  // Đảm bảo màu nền được áp dụng
                label.setFont(new Font("Segoe UI", Font.BOLD, 17));
                label.setHorizontalAlignment(SwingConstants.CENTER);  // Căn giữa văn bản
                return label;
            }
        });

        // Thiết lập DefaultTableCellRenderer để căn giữa
        DefaultTableCellRenderer centerRenderer = new DefaultTableCellRenderer();
        centerRenderer.setHorizontalAlignment(SwingConstants.CENTER);

        // Áp dụng renderer này cho tất cả các cột
        for (int i = 0; i < tblBev.getColumnCount(); i++) {
            TableColumn column = tblBev.getColumnModel().getColumn(i);
            column.setCellRenderer(centerRenderer);
        }

        tblBev.setRowHeight(50);

        tblBev.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_INTERVAL_SELECTION);

        tblBev.getTableHeader().setReorderingAllowed(false);

        TableColumnModel columnModel = tblBev.getColumnModel();
        TableColumn col0 = columnModel.getColumn(0);
        TableColumn col1 = columnModel.getColumn(1);
        TableColumn col2 = columnModel.getColumn(2);
        TableColumn col3 = columnModel.getColumn(3);
        TableColumn col4 = columnModel.getColumn(4);

        col0.setPreferredWidth(30);
        col1.setPreferredWidth(120);
        col2.setPreferredWidth(20);
        col3.setPreferredWidth(80);
        col4.setPreferredWidth(100);
        tblBev.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);

        tblBev.getTableHeader().setResizingAllowed(false);
        for (int i = 0; i < tblBev.getColumnCount(); i++) {
            tblBev.getColumnModel().getColumn(i).setResizable(false);
        }
        tblBev.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        tblBev.setModel(tblModelBev);
        tblBev.setGridColor(new java.awt.Color(235, 228, 226));
        tblBev.setSelectionBackground(new java.awt.Color(102, 44, 33));
        tblBev.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblBevMouseClicked(evt);
            }
        });
        scroll.setViewportView(tblBev);
        scroll.getVerticalScrollBar().setUI(new CustomScrollBarUI());
        scroll.getViewport().setBackground(new Color(235, 228, 226));

        panelCenter.add(scroll, java.awt.BorderLayout.CENTER);

        add(panelCenter, java.awt.BorderLayout.CENTER);

        panelSouth.setBackground(new java.awt.Color(210, 180, 160));

        panelTotal.setBackground(new java.awt.Color(210, 180, 160));

        lblTotal.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        lblTotal.setText("Tổng nước uống");

        txtTotal.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N

        javax.swing.GroupLayout panelTotalLayout = new javax.swing.GroupLayout(panelTotal);
        panelTotal.setLayout(panelTotalLayout);
        panelTotalLayout.setHorizontalGroup(
            panelTotalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelTotalLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(lblTotal, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(20, 20, 20)
                .addComponent(txtTotal, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        panelTotalLayout.setVerticalGroup(
            panelTotalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelTotalLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(panelTotalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(txtTotal, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(lblTotal, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout panelSouthLayout = new javax.swing.GroupLayout(panelSouth);
        panelSouth.setLayout(panelSouthLayout);
        panelSouthLayout.setHorizontalGroup(
            panelSouthLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
            .addGroup(panelSouthLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(panelSouthLayout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(panelTotal, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addContainerGap()))
        );
        panelSouthLayout.setVerticalGroup(
            panelSouthLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
            .addGroup(panelSouthLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelSouthLayout.createSequentialGroup()
                    .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(panelTotal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
        );

        add(panelSouth, java.awt.BorderLayout.SOUTH);
    }// </editor-fold>//GEN-END:initComponents

    private void txtSearchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtSearchActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtSearchActionPerformed

    private void btnSearchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSearchActionPerformed
        tblModelBev.setRowCount(0);
        String find = txtSearch.getText();
        Beverage b = db.findById(find);
        if (b != null) {
            tblModelBev.addRow(new Object[]{b.getCategory().getName(), b.getBeverageID(),
                b.getName(), b.getSellingPrice(), b.isDiscontinued(), b.getImgPath()});

            int countBev = db.findAll().size();
            if (countBev > 0) {
                txtTotal.setText(countBev + "");
            } else {
                txtTotal.setText("0");
            }

            String nameCatBev = tblModelBev.getValueAt(row, 0).toString();
            Category c = dc.findByName(nameCatBev);
            cbbNameCatBev.setSelectedItem(c.getCategoryID());
            txtNameBev.setText(tblModelBev.getValueAt(row, 2).toString());
            txtPriceBev.setText(tblModelBev.getValueAt(row, 3).toString());
            if (tblModelBev.getValueAt(row, 4).toString() == "true") {
                cbDiscontinued.setSelected(true);
            } else {
                cbDiscontinued.setSelected(false);
            }

        } else {
            clearTextField();
            loadData();
            JOptionPane.showMessageDialog(this, "Không tìm thấy!");
        }
    }//GEN-LAST:event_btnSearchActionPerformed


    private void cbbNameCatBevActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbbNameCatBevActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cbbNameCatBevActionPerformed

    private void txtNameBevActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtNameBevActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtNameBevActionPerformed

    private void txtPriceBevActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtPriceBevActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtPriceBevActionPerformed

    private void btnImgActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnImgActionPerformed
        JFileChooser fileChooser = new JFileChooser();
        FileNameExtensionFilter imgFilter = new FileNameExtensionFilter("hinh anh", "jpg");
        fileChooser.setFileFilter(imgFilter);
        fileChooser.setMultiSelectionEnabled(false);

        int x = fileChooser.showDialog(this, "Choose file");
        if (x == JFileChooser.APPROVE_OPTION) {
            File f = fileChooser.getSelectedFile();
            
            String imgPath = f.getAbsolutePath();
            imgPathCut = imgPath.substring(imgPath.lastIndexOf("\\") + 1);
            File newF = new File("./src/img/" + f.getName());
            try {
                // Copy file
                Files.copy(f.toPath(), newF.toPath(), StandardCopyOption.REPLACE_EXISTING);

                BufferedImage originalImage = ImageIO.read(f);

                // Kích thước mới
                int newWidth = 100;
                int newHeight = 100;

                // Resize ảnh
                BufferedImage resizedImage = new BufferedImage(newWidth, newHeight, BufferedImage.TYPE_INT_ARGB);
                Graphics2D g = resizedImage.createGraphics();
                g.drawImage(originalImage, 0, 0, newWidth, newHeight, null);
                g.dispose();

                // Hiển thị ảnh đã resize trên JLabel
                lblImg.setIcon(new ImageIcon(resizedImage));
            } catch (IOException ex) {
                ex.printStackTrace();
            }
        }
    }//GEN-LAST:event_btnImgActionPerformed

    private void btnAddActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAddActionPerformed

        if (valiData()) {
            Beverage bev = revertBeverageFromTextFields();

            db.insert(bev);
            tblModelBev.addRow(new Object[]{dc.findById(bev.getCategory().getCategoryID()).getName(),
                bev.getBeverageID(), bev.getName(), bev.getSellingPrice(), false, imgPathCut});

            int countBev = db.findAll().size();
            if (countBev > 0) {
                txtTotal.setText(countBev + "");
            } else {
                txtTotal.setText("0");
            }

            JOptionPane.showMessageDialog(this, "Thêm thành công!");
        }


    }//GEN-LAST:event_btnAddActionPerformed
    private void clearTextField() {
        txtSearch.setText("");
        txtNameBev.setText("");
        txtPriceBev.setText("");
        cbDiscontinued.setSelected(false);
    }

    private boolean valiData() {
        String catBev = cbbNameCatBev.getSelectedItem().toString();
        double taxBev = 0;
        String nameBev = txtNameBev.getText().trim();
        String price = txtPriceBev.getText().trim();
        double priceBev = 0;
        if (nameBev.equals("")) {
            errorNameBev.setForeground(Color.red);
            errorNameBev.setText("Tên không hợp lệ!");
            return false;
        } else {
            errorNameBev.setForeground(Color.green);
            errorNameBev.setText("");

        }

        if (!price.matches("[0-9]+")) {
            errorPriceBev.setForeground(Color.red);
            errorPriceBev.setText("Giá không hợp lệ");
            return false;
        } else {
            priceBev = Double.parseDouble(price);
            errorPriceBev.setForeground(Color.green);
            errorPriceBev.setText("");

        }
        return true;
    }

    private Beverage revertBeverageFromTextFields() {
        String catBev = cbbNameCatBev.getSelectedItem().toString();
        double taxBev = 0;
        String nameBev = txtNameBev.getText().trim();
        String price = txtPriceBev.getText().trim();
        double priceBev = Double.parseDouble(price);

        Beverage newBev = new Beverage(dc.findById(catBev), nameBev, priceBev);

        return new Beverage(newBev.getBeverageID(), nameBev,
                LocalDateTime.now(), false,
                priceBev, 0, imgPathCut, dc.findById(catBev));
    }
    private void btnUpdateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnUpdateActionPerformed
        int row = tblBev.getSelectedRow();
//        String catBev = cbbNameCatBev.getSelectedItem().toString();
        String catBev = tblModelBev.getValueAt(row, 0).toString();
        String nameBev = txtNameBev.getText().trim();
        String bevID = tblModelBev.getValueAt(row, 1).toString();
        double priceBev = Double.parseDouble(txtPriceBev.getText().trim());
        boolean disBev = cbDiscontinued.isSelected();
        String image = tblModelBev.getValueAt(row, 5).toString();

        if (valiData()) {

            Beverage b = db.findById(bevID);

            Beverage newBev = new Beverage(b.getBeverageID(), nameBev,
                    LocalDateTime.now(), disBev,
                    priceBev, 0, image, db.findById(bevID).getCategory());

            int option = JOptionPane.showConfirmDialog(this, "Bạn có chắc chắn muốn cập nhật thông tin?", "Xác nhận", JOptionPane.YES_NO_OPTION);
            if (option == JOptionPane.YES_OPTION) {
                tblModelBev.setValueAt(catBev, row, 0);
                tblModelBev.setValueAt(nameBev, row, 2);
                tblModelBev.setValueAt(priceBev, row, 3);
                tblModelBev.setValueAt(disBev, row, 4);
                tblModelBev.setValueAt(image, row, 5);
                db.update(newBev);
            }

        }


    }//GEN-LAST:event_btnUpdateActionPerformed

    private void tblBevMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblBevMouseClicked
        int row = tblBev.getSelectedRow();
        String nameCatBev = tblModelBev.getValueAt(row, 0).toString();
        Category c = dc.findByName(nameCatBev);
        cbbNameCatBev.setSelectedItem(c.getCategoryID());
        txtNameBev.setText(tblModelBev.getValueAt(row, 2).toString());
        txtPriceBev.setText(tblModelBev.getValueAt(row, 3).toString());
        if (tblModelBev.getValueAt(row, 4).toString() == "true") {
            cbDiscontinued.setSelected(true);
        } else {
            cbDiscontinued.setSelected(false);
        }


    }//GEN-LAST:event_tblBevMouseClicked

    private void cbDiscontinuedActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbDiscontinuedActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cbDiscontinuedActionPerformed
    public void loadData() {
        List<Beverage> listTopBev = db.getListTopBev();
        for (Beverage bev : listTopBev) {
            tblModelBev.addRow(new Object[]{bev.getCategory().getName(),
                bev.getBeverageID(), bev.getName(),
                bev.getSellingPrice(), bev.isDiscontinued(), bev.getImgPath()});
            int countBev = db.findAll().size();
            if (countBev > 0) {
                txtTotal.setText(countBev + "");
            } else {
                txtTotal.setText("0");
            }
        }

        int count = dc.findAll().size();
        for (int i = 0; i < count; i++) {
            cbbNameCatBev.addItem(dc.findAll().get(i).getCategoryID());
        }

    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Discontinued;
    private javax.swing.JButton btnAdd;
    private javax.swing.JButton btnImg;
    private javax.swing.JButton btnSearch;
    private javax.swing.JButton btnUpdate;
    private javax.swing.JCheckBox cbDiscontinued;
    private static javax.swing.JComboBox<String> cbbNameCatBev;
    private javax.swing.JLabel errorNameBev;
    private javax.swing.JLabel errorPriceBev;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanelimg;
    private javax.swing.JLabel lblImg;
    private javax.swing.JLabel lblNameBev;
    private javax.swing.JLabel lblNameCatBev;
    private javax.swing.JLabel lblPriceBev;
    private javax.swing.JLabel lblSearch;
    private javax.swing.JLabel lblTotal;
    private javax.swing.JPanel panelButton;
    private javax.swing.JPanel panelCenter;
    private javax.swing.JPanel panelInfo;
    private javax.swing.JPanel panelInfoLeft;
    private javax.swing.JPanel panelInfoRight;
    private javax.swing.JPanel panelNameBev;
    private javax.swing.JPanel panelNameCatBev;
    private javax.swing.JPanel panelNorth;
    private javax.swing.JPanel panelPriceBev;
    private javax.swing.JPanel panelSearch;
    private javax.swing.JPanel panelSouth;
    private javax.swing.JPanel panelTotal;
    private javax.swing.JPanel panelmgBev;
    private javax.swing.JScrollPane scroll;
    private javax.swing.JTable tblBev;
    private javax.swing.JTextField txtNameBev;
    private javax.swing.JTextField txtPriceBev;
    private javax.swing.JTextField txtSearch;
    private javax.swing.JLabel txtTotal;
    // End of variables declaration//GEN-END:variables
}
