/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package gui;

import gui.custom.CustomComboBox;
import gui.custom.CustomRectangularButton;
import gui.custom.CustomTabbedPane;
import dao.DAOOrder;
import java.awt.Color;
import java.awt.Frame;
import java.time.LocalDate;
import java.util.List;
import java.util.Map;
import javax.swing.GroupLayout;
import javax.swing.SwingUtilities;

/**
 *
 * @author pc
 */
public class Stats extends javax.swing.JPanel {
    
    private DAOOrder dod = new DAOOrder();

    /**
     * Creates new form NewStatistic
     */
    public Stats() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        jTabbedPane1 = new javax.swing.JTabbedPane();
        tab1 = new javax.swing.JPanel();
        jPanel4 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        cBBYearTabY = new CustomComboBox(getYearsCbbData());
        btnStatsYear = new CustomRectangularButton(new Color[]{Color.white , new Color(102, 44, 33), new Color(131, 85, 76)});
        panelChartYeat = new javax.swing.JPanel();
        chartYear = createYearlyPanelChart();
        tab2 = new javax.swing.JPanel();
        panelChartMonth = new javax.swing.JPanel();
        cBBYearTabM = new CustomComboBox(getYearsCbbData());

        currentYear = LocalDate.now().getYear();
        cBBYearTabM.setSelectedItem(String.valueOf(currentYear));
        chartMonth = createMonthlyPanelChart();
        jPanel1 = new javax.swing.JPanel();
        jPanel5 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        cBBYearTabM = new CustomComboBox(getYearsCbbData());
        jPanel7 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        cBBMonthTabM = new CustomComboBox(getMonthsCbbData());
        btnStatsMonth = new CustomRectangularButton(new Color[]{new Color(254, 225, 191), new Color(102, 44, 33), new Color(131, 85, 76)});

        setLayout(new java.awt.BorderLayout());

        jPanel2.setBackground(new java.awt.Color(210, 180, 160));
        jPanel2.setLayout(new java.awt.BorderLayout());

        jTabbedPane1.setUI(new CustomTabbedPane());
        jTabbedPane1.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jTabbedPane1.setPreferredSize(new java.awt.Dimension(701, 700));

        tab1.setBackground(new java.awt.Color(210, 180, 160));
        tab1.setLayout(new java.awt.BorderLayout());

        jPanel4.setBackground(new java.awt.Color(210, 180, 160));
        jPanel4.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.LEFT));

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel1.setText("Chọn năm: ");
        jPanel4.add(jLabel1);

        cBBYearTabY.setMaximumRowCount(4);
        int currentYear = LocalDate.now().getYear();
        cBBYearTabY.setSelectedItem(String.valueOf(currentYear));
        cBBYearTabY.setPreferredSize(new java.awt.Dimension(72, 25));
        cBBYearTabY.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cBBYearTabYActionPerformed(evt);
            }
        });
        jPanel4.add(cBBYearTabY);

        btnStatsYear.setText("Thống kê");
        btnStatsYear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnStatsYearActionPerformed(evt);
            }
        });
        jPanel4.add(btnStatsYear);

        tab1.add(jPanel4, java.awt.BorderLayout.PAGE_START);

        panelChartYeat.setBackground(new java.awt.Color(210, 180, 160));

        RevenueChart rYear = chartYear.getRevenueChart();
        rYear.setChartTitle("BIỂU ĐỒ THỐNG KÊ DOANH THU GIAI ĐOẠN " + dod.getYearPeriod());
        rYear.setxName("Năm");
        chartYear.setRevenueChart(rYear);

        javax.swing.GroupLayout panelChartYeatLayout = new javax.swing.GroupLayout(panelChartYeat);
        panelChartYeat.setLayout(panelChartYeatLayout);
        panelChartYeatLayout.setHorizontalGroup(
            panelChartYeatLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelChartYeatLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(chartYear, javax.swing.GroupLayout.DEFAULT_SIZE, 689, Short.MAX_VALUE)
                .addContainerGap())
        );
        panelChartYeatLayout.setVerticalGroup(
            panelChartYeatLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelChartYeatLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(chartYear, javax.swing.GroupLayout.DEFAULT_SIZE, 567, Short.MAX_VALUE)
                .addContainerGap())
        );

        tab1.add(panelChartYeat, java.awt.BorderLayout.CENTER);

        jTabbedPane1.addTab("Năm", tab1);

        tab2.setLayout(new java.awt.BorderLayout());

        panelChartMonth.setBackground(new java.awt.Color(210, 180, 160));

        RevenueChart rMonth = chartMonth.getRevenueChart();
        rMonth.setChartTitle("BIỂU ĐỒ THỐNG KÊ DOANH THU CÁC THÁNG TRONG NĂM 2024");
        rMonth.setxName("Tháng");
        chartMonth.setRevenueChart(rMonth);

        javax.swing.GroupLayout panelChartMonthLayout = new javax.swing.GroupLayout(panelChartMonth);
        panelChartMonth.setLayout(panelChartMonthLayout);
        panelChartMonthLayout.setHorizontalGroup(
            panelChartMonthLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelChartMonthLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(chartMonth, javax.swing.GroupLayout.DEFAULT_SIZE, 689, Short.MAX_VALUE)
                .addContainerGap())
        );
        panelChartMonthLayout.setVerticalGroup(
            panelChartMonthLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelChartMonthLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(chartMonth, javax.swing.GroupLayout.DEFAULT_SIZE, 532, Short.MAX_VALUE)
                .addContainerGap())
        );

        tab2.add(panelChartMonth, java.awt.BorderLayout.CENTER);

        jPanel1.setBackground(new java.awt.Color(210, 180, 160));

        jPanel5.setBackground(new java.awt.Color(210, 180, 160));
        jPanel5.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.LEFT));

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel2.setText("Chọn năm: ");
        jPanel5.add(jLabel2);

        cBBYearTabM.setMaximumRowCount(4);
        currentYear = LocalDate.now().getYear();
        cBBYearTabM.setSelectedItem(String.valueOf(currentYear));
        cBBYearTabM.setPreferredSize(new java.awt.Dimension(72, 25));
        cBBYearTabM.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cBBYearTabMActionPerformed(evt);
            }
        });
        jPanel5.add(cBBYearTabM);

        jPanel7.setBackground(new java.awt.Color(210, 180, 160));
        jPanel7.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.LEFT));

        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel3.setText("Chọn tháng: ");
        jPanel7.add(jLabel3);
        jLabel2.setPreferredSize(jLabel3.getPreferredSize());

        cBBMonthTabM.setMaximumRowCount(4);
        int currentMonth = LocalDate.now().getMonthValue();
        cBBMonthTabM.setSelectedItem(String.valueOf(currentMonth));
        cBBMonthTabM.setPreferredSize(new java.awt.Dimension(72, 25));
        jPanel7.add(cBBMonthTabM);

        btnStatsMonth.setText("Thống kê");
        btnStatsMonth.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnStatsMonthActionPerformed(evt);
            }
        });
        jPanel7.add(btnStatsMonth);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jPanel7, javax.swing.GroupLayout.DEFAULT_SIZE, 701, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(jPanel7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        tab2.add(jPanel1, java.awt.BorderLayout.NORTH);

        jTabbedPane1.addTab("Tháng", tab2);

        jPanel2.add(jTabbedPane1, java.awt.BorderLayout.CENTER);

        add(jPanel2, java.awt.BorderLayout.CENTER);
    }// </editor-fold>//GEN-END:initComponents

    private void btnStatsYearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnStatsYearActionPerformed
        DialogStats dialog = new DialogStats((Frame) SwingUtilities.getWindowAncestor(this), true);
        int year = Integer.parseInt(cBBYearTabY.getSelectedItem().toString());
        dialog.setLblYear("Doanh Thu Năm " + year);
        dialog.setLblRevenue(dod.getYearRevenue(year));
        dialog.setLblSoLuong(dod.getYearSoLuong(year));
        dialog.setTable(year);
        dialog.setVisible(true);
    }//GEN-LAST:event_btnStatsYearActionPerformed

    private void cBBYearTabMActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cBBYearTabMActionPerformed
 
        chartMonth = createMonthlyPanelChart();

        GroupLayout panelChartMonthLayout = new javax.swing.GroupLayout(panelChartMonth);
        panelChartMonth.setLayout(panelChartMonthLayout);
        panelChartMonthLayout.setHorizontalGroup(
            panelChartMonthLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelChartMonthLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(chartMonth, javax.swing.GroupLayout.DEFAULT_SIZE, 688, Short.MAX_VALUE)
                .addContainerGap())
        );
        panelChartMonthLayout.setVerticalGroup(
            panelChartMonthLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelChartMonthLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(chartMonth, javax.swing.GroupLayout.DEFAULT_SIZE, 351, Short.MAX_VALUE)
                .addContainerGap())
        );

        
        tab2.add(panelChartMonth, java.awt.BorderLayout.CENTER);
        
        RevenueChart rMonth = chartMonth.getRevenueChart();
        rMonth.setChartTitle("BIỂU ĐỒ THỐNG KÊ DOANH THU CÁC THÁNG TRONG NĂM " + cBBYearTabM.getSelectedItem().toString());
        chartMonth.setRevenueChart(rMonth);
    }//GEN-LAST:event_cBBYearTabMActionPerformed

    private void btnStatsMonthActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnStatsMonthActionPerformed
        DialogStats dialog = new DialogStats((Frame) SwingUtilities.getWindowAncestor(this), true);
        int year = Integer.parseInt(cBBYearTabM.getSelectedItem().toString());
        int month = Integer.parseInt(cBBMonthTabM.getSelectedItem().toString());

        dialog.setLblYear("Doanh Thu Tháng " + month + "-" + year);
        dialog.setLblRevenue(dod.getMonthRevenue(year, month));
        dialog.setLblSoLuong(dod.getMonthSoLuong(year, month));
        dialog.setTable(year, month);
        dialog.setVisible(true);
    }//GEN-LAST:event_btnStatsMonthActionPerformed

    private void cBBYearTabYActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cBBYearTabYActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cBBYearTabYActionPerformed

    private String[] getYearsCbbData() {
        List<String> years = dod.getAllYear();
        return years.toArray(new String[0]);
    }

    private String[] getMonthsCbbData() {
        String[] months = new String[12];
        for (int i = 0; i < 12; i++) {
            months[i] = String.valueOf(i + 1);
        }
        return months;
    }

    private String[] getDaysCbbData() {
        String[] days = new String[31];
        for (int i = 0; i < 31; i++) {
            days[i] = String.valueOf(i + 1);
        }
        return days;
    }

    private PanelChart createYearlyPanelChart() {
        Map<Integer, Double> yearSumMap = dod.getYearlyOrderSums();
        
        
        Integer[] yearArray = yearSumMap.keySet().toArray(new Integer[0]);
        Double[] sumArray = yearSumMap.values().toArray(new Double[0]);
        
        return new PanelChart(yearArray, sumArray);
    }

    private PanelChart createMonthlyPanelChart() {
        int year = Integer.parseInt(cBBYearTabM.getSelectedItem().toString());

        Map<Integer, Double> monthSumMap = dod.getMonthlyOrderSums(year);
        
        Integer[] monthArray = monthSumMap.keySet().toArray(new Integer[0]);
        Double[] sumArray = monthSumMap.values().toArray(new Double[0]);
        
        return new PanelChart(monthArray, sumArray);
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnStatsMonth;
    private javax.swing.JButton btnStatsYear;
    private javax.swing.JComboBox<String> cBBMonthTabM;
    private javax.swing.JComboBox<String> cBBYearTabM;
    private javax.swing.JComboBox<String> cBBYearTabY;
    private gui.PanelChart chartMonth;
    private int currentYear;
    private gui.PanelChart chartYear;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JPanel panelChartMonth;
    private javax.swing.JPanel panelChartYeat;
    private javax.swing.JPanel tab1;
    private javax.swing.JPanel tab2;
    // End of variables declaration//GEN-END:variables
}
